
<?php ?>
<div id="main-wrapper" >

    <section id="features" class="container">
        <div class="container col-lg-10 " style="margin-left: 50px;">

            <div class="jumbotron">
                <h1 class="display-3">Cadastro Efectuado com sucesso </h1>
                <p class="lead"></p>
                <hr class="my-4">
                <p>Foi enviado um email para sua caixa de mensagem com o link de ativação do mesmo da sua conta</p>
                <p>Por favor, consulta tua caiza de email</p>
                <p>Obrigado</p>
                <p class="lead">
                </p>
            </div>
        </div>
    </section>
</div>
