
<?php ?>
<div id="main-wrapper" >

    <section id="features" class="container">
        <div class="container col-lg-10 " style="margin-left: 50px;">

            <div class="jumbotron">
                <h1 class="display-3">E-mail Confirmado </h1>
                <p class="lead"></p>
                <hr class="my-4">
                <p>Obriado por confirmar o seu email, agora ja pode fazer  login.</p>
                <p class="lead">
                    <a class="btn btn-success " href="<?php echo URL; ?>user/login" role="button">Login</a>
                </p>
            </div>
        </div>
    </section>
</div>
<?php
