<?php
/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */
use Ballybran\Helpers\Security\Session;
use Ballybran\Library\Form;


if (!Session::exist()) :
    ?>

    <div class="container">
        <section>

            <div id="content" class="col-sm-6">
                    <h2>Register Account</h2>
                    <p>By creating an account you will be able to all faster, be up to date on an order's status, and keep track of the data you have previously made.</p>

                    <div class="form-group">
                        <a href="<?php echo URL; ?>user/signUp" class="form-button-submit button">continue</a>

                    </div>
            </div> <!-- end contend and col-sm-6 -->


            <div id="content" class="col-sm-6">

                    <h2>Login</h2>

                    <?php
                    echo Form::open(['method' => 'post', 'action'=> URL.'User/signIn', 'name' => 'signIn', 'class' => 'form-horizontal', 'style' => 'margin-left:10%;']);
                    ?>

                        <label class="control-label" for="input-firstname">Username</label>

                        <?php
                        echo Form::input(['type' => 'text', 'name' => 'email', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Insere seu numero ou email de Login']);
                        ?>
                        <p><strong><a class="text-blue right" href="<?php echo URL;?>user/formreset">Esqueceu sua senha?</a></strong></p>
                        <label class="control-label" for="input-password">Password</label>

                        <?php
                        echo Form::input(['type' => 'password', 'name' => 'password', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Password']);
                        ?>

                        <?php
                        echo Form::button(['type' => 'submit', 'class' => 'form-button-submit button', 'id' => 'send_request', 'value' => 'Login']);
                        ?>


                    <?php
                    echo Form::close();
                    ?>
            </div> <!-- end contend and col-sm-6 -->

        </section>
    </div>

<?php else : ?>
    <script>

        location.href:"<?php URL;?>Cpanel";
    </script>


<?php endif; ?>


<script>

    function signIn() {
        var username = $('form[name=signIn] input[name=username]')[0].value;
        var password = $('form[name=signIn] input[name=password]')[0].value;

        $.ajax({
            type: 'POST',
            url: '<?php echo URL;?>User/signIn',
            data: {username: username, password: password}
        }).done(function (resposta) {
            if (resposta == 1) {

            document.location= "<?php echo  URL;?>User/signIn";
            } else {

                alert("falhou");
            }
        });

    }
</script>
