
<?php
 Module\Lib2\header::getHeader();
?>
<div id="main-wrapper">

    <section id="features" class="container">
        <div class="container col-lg-10">

            <div class="row">
            <form  class="form-horizontal" action="<?php echo URL; ?>user/makePassword" name="perfil" method="post">

                <div class="form-group">
                    <label for="exampleInputPassword1">Digite seu endereço de e-mail e nós lhe enviaremos um link para redefinir sua senha.</label>
                    <input type="password" class="form-control" placeholder="nova senha" name="password">
                    <input type="hidden" class="form-control" value="<?php echo $this->id;?>" name="id">
                    <input type="hidden" class="form-control" value="<?php echo $this->email;?>" name="email">
                    <br>
                </div>

                <div class="col-sm-8">
                    <button type="submit" class="btn btn-info">Criar</button>
                </div>

            </form>
            </div>
        </div>
    </section>
</div>
<?php
 Module\Lib2\header::getFooter();
