<?php
 Module\Lib2\header::getHeader();

?>

<div id="main-wrapper">

    <section id="features" class="container">
        <div class="container col-lg-10">

                <div class="row">
                    <form  class="form-horizontal" action="<?php echo URL; ?>user/resetpassword" name="perfil" method="post">

                        <div class="form-group">
                            <label for="exampleInputPassword1">Digite seu endereço de e-mail e nós lhe enviaremos um link para redefinir sua senha.</label>
                            <input type="email" class="form-control" placeholder="E-mail" name="email">
                            <br>
                        </div>

                        <div class="col-sm-8">
                            <button type="submit" class="btn btn-info">Enviar</button>
                        </div>

                    </form>
                </div>
        </div>
    </section>
</div>
    <?php
     Module\Lib2\header::getFooter();



