<?php
/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

use Module\menu\Sub_Menu;
use Ballybran\Helpers\Security\Session;
use Ballybran\Library\Form;
Sub_Menu::getSubMenu();
?>


<div class="container" id="features" >
    <div class="breadcrumb text-center" id="features">
        <strong>Consultas feitas</strong>
    </div>
    <div class="row ">

        <?php foreach ($this->info as $item => $value) { ?>
        <div class="col-lg-3 4u 12u(mobile)">
                <strong><h3>Ultima consulta</h3></strong>
                <strong>Informação:</strong>
                <textarea disabled="disabled" cols="40" rows="10">
                    <?php echo $value['info']; ?>
                </textarea>
            </div>
        <?php } ?>

    </div>
</div>

<div class="container" id="features" style="margin-left: 35%;">
    <div class="row ">
        <div class="col-lg-3 4u 12u(mobile)">
            <strong><h3>Faz a sua consulta</h3></strong>
            <p>Para agendar sua consulta</p>
            <p>Escreva o que voçe sente na cacha ao lado</p>
            <p>E em seguida vai receber o horario da consulta</p>
            <p>ou lique - +244 936 695 474
                (Das 07:00 às 17:00 horas)</p>

            <?php
            echo Form::open(['action'=>URL .'Paciente/inserconsulta', 'method'=>'post']);
            echo Form::input(['type'=>'hidden', 'name'=>'usuarios_id', 'value'=> Session::get('ID')]);
            echo Form::textBox(['type'=>'text', 'name'=>'info', 'placeholder'=> 'Escreve aqui...']);
            echo Form::button(['name'=> 'submit', 'value'=>'Fazer consulta']);
            echo Form::close();

            ?>
        </div>
        <div class="col-lg-3 4u 12u(mobile)">

        </div>
    </div>
</div>

