<?php
/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

use Module\menu\Sub_Menu;
use Ballybran\Helpers\Security\Session;
use Ballybran\Library\Form;
Sub_Menu::getSubMenu();
?>


<div class="container">
    <div class="breadcrumb text-center" id="features">
        <strong>Marcar Consulta</strong>
    </div>
    <div class="row ">
            <div class="col-lg-4 ">
                <p>Escreva o que voçe sente na cacha ao lado</p>
            </div>
        <div class="col-lg-4 ">
            <?php
            echo Form::open(['action'=>URL .'Paciente/inserconsulta', 'method'=>'post']);
            echo Form::input(['type'=>'hidden', 'name'=>'usuarios_id', 'value'=> $this->id ]);
            echo Form::textBox(['type'=>'text', 'name'=>'info', 'placeholder'=> 'Escreve aqui...']);
            echo Form::button(['name'=> 'submit', 'value'=>'Fazer consulta']);
            echo Form::close();

            ?>
        </div>
        <div class="col-lg-4 ">

        </div>
    </div>
</div>

