<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */
use Ballybran\Library\Form;
\Module\menu\Sub_Menu::getSubMenu();
?>
<section>
    <div class="container col-sm-12">
        <div class="breadcrumb text-center title-top-center" id="features" >
        <strong> <h3>Distribuição de Pacientes</h3></strong>
        </div>

        <table class="col-lg-12 table  table-black table-responsive table-bordered pull-right">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Telefone</th>
                    <th>Privilegio</th>
                    <th>Informação</th>
                    <th>Atribuir Medico</th>
                    <th>Marcar Horas</th>
                    <th>Atualizar</th>
                    <th>deletar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->consultas as $key => $value) { ?>
                    <tr>
                        <td><?php echo $value['firstname'] . "\n" . $value['lastname']; ?></td>
                        <td><?php echo $value['telephone']; ?></td>
                        <td><?php echo $value['role']; ?></td>
                        <td><?php echo $value['info']; ?></td>
                            <?php

                            echo Form::open(['method'=> 'post', 'action'=> URL .'secretaria/joinPacienteAndFunc']);
                        echo Form::input(['type'=> 'hidden', 'name'=> 'Paciente_id', 'value'=> $value['id'] ]);
                        ?>
                        <td>
                        <select name="Funcionarios_id" style='color:#000000;'>
                            <?php foreach ($this->func as $keys => $val ) :?>
                                ?
                                <option>--</option>
                            <option value="<?php echo $val['id']; ?>"><?php echo $val['firstname']; ?> </option>

                            <?php endForeach; ?>
                        </select>
                        </td>

                        <td>
                            <?php
                            echo Form::input(['type'=> 'time', 'name'=> 'horas', 'style'=>'color:#000000;', 'placeholder'=> 'horas' ]);
                            ?>
                        </td>
                        <td>
                            <?php echo Form::submit(['type'=> 'submit', 'value'=> 'Atualizar']); ?>
                        </td>
                        <?php

                        echo Form::close();
                        ?>
                        <td><a class="btn btn-danger" href="<?php echo URL ?>secretaria/deletes/<?php echo $value['id']; ?>"><i class="glyphicon glyphicon-trash "></i></td>



                    </tr>
                <?php } ?>

            </tbody>
        </table>
        <?php if ($this->consultas == "" || empty($this->consultas)) echo "<h3>Está vazio :) </h3><br><br>"; ?>

    </div>
</section><!-- Call to action -->




<div style="height:40px;"></div>
<div class="assessment-container container">
    <div class="row">
        <div class="col-md-6 form-box">
            <form role="form" class="registration-form" action="javascript:void(0);">
                <fieldset>
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3><span><i class="fa fa-calendar-check-o" aria-hidden="true"></i></span>Lorem ipsum dolor sit amet</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit
                            </p>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <div class="row">
                            <div class="form-group col-md-6 col-sm-6">
                                <input type="text" class="form-control" placeholder="Firstname" id="fname">
                            </div>
                            <div class="form-group col-md-6 col-sm-6">
                                <input type="text" class="form-control" placeholder="Lastname" id="lname">
                            </div>
                        </div>
                        <div class="form-group" style="margin-bottom:3px;">
                            <div class="row">
                                <div class="form-group col-md-3 col-sm-3">
                                    <select class="form-control">
                                        <option>00</option>
                                        <option>00</option>
                                        <option>00</option>
                                        <option>00</option>
                                        <option>00</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-9 col-sm-9">
                                    <input type="text" class="form-control" placeholder="Contact Number" id="contact_number">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="text" name="email" placeholder="Email" class="form-email form-control" id="email" required>
                        </div>

                        <div class="form-group">
                            <select class="form-control">
                                <option>Gender</option>
                                <option>Male</option>
                                <option>Female</option>
                            </select>
                        </div>

                        <button type="button" class="btn btn-next">Next</button>
                    </div>
                </fieldset>
                <fieldset>
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3><span><i class="fa fa-calendar-check-o" aria-hidden="true"></i></span> Lorem ipsum dolor sit amet</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit
                            </p>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <div class="form-group">
                            <select class="form-control">
                                <option>Location</option>
                                <option>Location</option>
                                <option>Location</option>
                                <option>Location</option>
                                <option>Locationa</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="date" class="form-control" id="pref_date">
                        </div>
                        <div class="form-group">
                            <select class="form-control">
                                <option>Preffered Time</option>
                                <option>Location</option>
                                <option>Location</option>
                                <option>Location</option>
                                <option>Location</option>
                                <option>Locationa</option>
                            </select>
                        </div>
                        <button type="button" class="btn btn-previous">Previous</button>
                        <button type="submit" class="btn">Submit</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>