<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */
use Ballybran\Library\Form;
\Module\menu\Sub_Menu::getSubMenu();
?>
<section>
    <div class="container col-sm-12">
        <div class="breadcrumb text-center title-top-center" id="features" >
        <strong> <h3>Distribuição de Pacientes</h3></strong>
        </div>

        <table class="col-lg-12 table  table-black table-responsive table-bordered pull-right">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Telefone</th>
                    <th>Privilegio</th>
                    <th>Informação</th>
                    <th>Atribuir Medico</th>
                    <th>Marcar Horas</th>
                    <th>Atualizar</th>
                    <th>deletar</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->consultas as $key => $value) { ?>
                    <tr>
                        <td><?php echo $value['firstname'] . "\n" . $value['lastname']; ?></td>
                        <td><?php echo $value['telephone']; ?></td>
                        <td><?php echo $value['role']; ?></td>
                        <td><?php echo $value['info']; ?></td>
                            <?php

                            echo Form::open(['method'=> 'post', 'action'=> URL .'secretaria/joinPacienteAndFunc']);
                        echo Form::input(['type'=> 'hidden', 'name'=> 'Paciente_id', 'value'=> $value['id'] ]);
                        ?>
                        <td>
                        <select name="Funcionarios_id" style='color:#000000;'>
                            <?php foreach ($this->func as $keys => $val ) :?>
                                ?
                                <option>--</option>
                            <option value="<?php echo $val['id']; ?>"><?php echo $val['firstname']; ?> </option>

                            <?php endForeach; ?>
                        </select>
                        </td>

                        <td>
                            <?php
                            echo Form::input(['type'=> 'time', 'name'=> 'horas', 'style'=>'color:#000000;', 'placeholder'=> 'horas' ]);
                            ?>
                        </td>
                        <td>
                            <?php echo Form::submit(['type'=> 'submit', 'value'=> 'Atualizar']); ?>
                        </td>
                        <?php

                        echo Form::close();
                        ?>
                        <td><a class="btn btn-danger" href="<?php echo URL ?>secretaria/deletes/<?php echo $value['id']; ?>"><i class="glyphicon glyphicon-trash "></i></td>



                    </tr>
                <?php } ?>

            </tbody>
        </table>
        <?php if ($this->consultas == "" || empty($this->consultas)) echo "<h3>Está vazio :) </h3><br><br>"; ?>

    </div>
</section><!-- Call to action -->