<!DOCTYPE html>
<!--
copyright 16/JUL/2016 Marcio Zebedeu.

@author Marcio Zebedeu - marciozebedeu@artphoweb.com;

@version 1.0;
@date 16/JUL/2016 ;
@update 16/JUL/2016;
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->


<div class="container">
    <section>
        <div class="page-header text-center btn-default">
            <h2>Faça o Uploads de um ficheiro</h2>

        </div>
    </section>


