
<?php


 Module\Lib2\header::getHeader();

?>
<!-- { col-2 | col-3 | col-4 } -->

<?php use Ballybran\Helpers\Security\Session;
use Ballybran\Helpers\Time\Timestamp;

foreach ($this->public as $key => $value) { ?>

<div id="main-wrapper">

	<section id="features" class="container">

		<div class="container col-lg-10">
			<div class="row">
				 <header class="card-header col-lg-6">
									<h3 class="btn btn-default"><?php echo $value['title']; ?>
								   <strong><?php echo $value['post_date']; ?></strong></h3>
								   
								</header>
					<div class="thumbnail">
							<div>
<img class="col-lg-4 l  img-responsive img-circle" style="margin-left: 100px;"  src="<?php echo URL. $value['path'];?>" alt="">
						</div>

								<p> <?php echo $post = $value['content'] ?? null; ?></p>

								<?php
								/*
								  /* insert comments
								 */
								?>

					</div>
					<a href="<?php echo URL; ?>article">Voltar</a>
					<?php
					if (Session::exist()) {
						if (Session::get('role') == 'owner' || Session::get('role') == 'admin'):
							?>
							<a href=<?php echo URL; ?>article/editar/<?php echo $value['id_article'] ?>>editar</a>
							<?php
						endif;
					}
					?>

				<?php } ?>
			</div>
		<hr>
		<div class=" col-lg-6">
				<div class="well">

					<form method="post" name="signIn"  action="<?php echo URL; ?>Article/insertComments" id="anamneseForm" >

						<?php
						if (Session::exist()) {
							if (Session::get('role') == 'owner' || Session::get('role') == 'admin' || Session::get('role') == 'default' || Session::get('role') == 'funcionario' || Session::get('role') == 'paciente' || Session::get('role') == 'secretaria'):
								?>
								<div class="form-group">
									<input type="text" name="nome" class="form-control" value="<?php echo $this->getUser['firstname']." ".$this->getUser['lastname']?>">
								</div>
								<div class="form-group">
									<input type="text" name="email" class="form-control" value="<?php echo $this->getUser['email']?>">
								</div>
									<?php
								endif;
							} else {
								?>
								<div class="form-group">
									<input type="text" name="nome" class="form-control" placeholder="Seu nome" >
								</div>
								<div class="form-group">
									<input type="email" name="email" class="form-control" placeholder="E-mail" >
								</div>

								<?php } ?>

						<div class="form-group">
							<textarea type="text" name="comments"  class="form-control" placeholder="Coloca teu comenario aqui"></textarea>

						</div>
						<div class="form-group">
							<input type="hidden" name="article_id" class="form-control" value="<?php echo $value['id_article']; ?>">

						</div>

						<div class="form-group">
							<input type="hidden" name="post_date" class="form-control" value="<?php echo date('Y-m-d H:i:s'); ?>">

						</div>
					   <button type="submit" id="save"  class="btn btn-info btn-fill pull-right">Save</button>
														<div class="clearfix"></div>
					</form>
				</div>
			</div>


  <div class="container col-lg-10">

			<table  class="table table-responsive">
				<thead>
					<tr>
						<th>Nome</th>
						<th colspan="400">Comentarios</th>
						<?php
						if (Session::exist()) {
							if (Session::get('role') == 'owner' || Session::get('role') == 'admin' ) {
								?>
								<th>Deletar</th>
								<?php
							}
						}
						?>
					</tr>

				</thead>
				<tbody>

					<?php foreach ($this->comments as $key => $comm) { ?>
						<tr>

							<td colspan="400"><p class="glyphicon glyphicon-comment "><?php echo $comm['post_date']; ?> </p><em><?php echo "\n" . $comm['nome']; ?> <br> <?php echo Timestamp::distanceOfTimeInWords($comm['post_date'], time()); ?></em></td>
							<td><em><?php echo $comm['comments']; ?></em></td>


							<?php
							if (Session::exist()) {
								if (Session::get('role') == 'owner' || Session::get('role') == 'admin') {
									?>

									<td><a  href="<?php echo URL; ?>/article/deleteComments/<?php echo $comm['id']; ?>"><p class="btn btn-outline-primary   btn-default">deletar</p></a></td>
											<?php
										}
									}
									?>
						</tr>
				<?php } ?>

				</tbody>
			</table>
		</div>
	</section>
</div>

<script>


	 // function signIn() {
    //     var comments = $('form[name=signIn] input[name=comments]')[0].value;
    //     var nome = $('form[name=signIn] input[name=nome]')[0].value;
    //     var post_date = $('form[name=signIn] input[name=post_date]')[0].value;
    //     var email = $('form[name=signIn] input[name=email]')[0].value;

    //     $.ajax({
    //         type: 'POST',
    //         url: "<?php echo URL; ?>Article/insertComments",
    //         data: {comments: comments, nome: nome, post_date:post_date, email: email},
    //     sucess: function (data) {

    //         	alert(data);

    //         // document.location= "<?php echo  URL;?>User/signIn";

    //             alert("falhou");
    //         }
    //     });

    // }

	$("#save").click(function () {
		var data = $("#anamneseForm :input").serializeArray();
		$.post($("#anamneseForm").attr("action"), data, function (info) {
			$("result").html(info);

		});
	});

	$("#anamneseForm").submit(function () {
		return false;
	});

	function clearInfo() {
		$("#anamneseForm :input").each(function () {
			$(this).val("");
		});
	};

	function hideForm() {
		$("#anamneseForm").each(function () {
			$(this).hide("");
		});
	};

	function showSucessMessage() {
		$(".message").each(function () {
			$(".message").html("<div class='alert alert-info alert-with-icon' data-notify='container'> mensagem inserida com sucess").show();
		});
	};

</script>



