<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

use Ballybran\Helpers\Security\Session;
use Ballybran\Library\Form;
Module\Clinic\Lib\menu\Sub_Menu::getSubMenu();

$c = new \Ballybran\Core\Caller\Caller('Module\Lib\Visitor', 'contagem');
$d = $c->__init();

$register = \Ballybran\Database\RegistryDatabase::getInstance();
$stmt =  $register->get("PDO");
$atendido = $stmt->selectManager("SELECT * FROM Paciente INNER JOIN usuarios ON usuarios.id= Paciente.usuarios_id
                                                                    INNER JOIN Func_has_Paci ON Func_has_Paci.Paciente_id = Paciente.id
                                                                    INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id
                                                                    INNER JOIN Convenio ON Convenio.id = Paciente.Convenio_id 
                                                                    INNER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id AND Anamnese.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Docum_Atestado ON Docum_Atestado.Paciente_id = Paciente.id AND Docum_Atestado.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Evolucao ON Evolucao.Paciente_id = Paciente.id AND Evolucao.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Exame_Fisico ON Exame_Fisico.Paciente_id = Paciente.id AND Exame_Fisico.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN hipotese_diagnostica ON hipotese_diagnostica.Paciente_id = Paciente.id AND hipotese_diagnostica.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Medicamento ON Medicamento.Paciente_id = Paciente.id WHERE Funcionarios.usuarios_id=".Session::get("ID"));

$agendados =  $stmt->selectManager(" SELECT * FROM Paciente LEFT OUTER JOIN Anamnese on Paciente.id = Anamnese.Paciente_id  INNER JOIN Func_has_Paci on  Paciente.id = Func_has_Paci.Paciente_id INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id WHERE   Func_has_Paci.start > now() AND Anamnese.Paciente_id is null AND Funcionarios.usuarios_id = ".Session::get("ID")  );
$faltaram =  $stmt->selectManager("SELECT * FROM Paciente LEFT OUTER JOIN Anamnese on Paciente.id = Anamnese.Paciente_id  INNER JOIN Func_has_Paci on  Paciente.id = Func_has_Paci.Paciente_id INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id WHERE  Func_has_Paci.start < now() AND Anamnese.Paciente_id is null AND Funcionarios.usuarios_id =".Session::get("ID")  );

$mulher = $stmt->selectManager("SELECT * FROM Anamnese INNER JOIN Paciente ON Paciente.id = Anamnese.Paciente_id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id INNER JOIN Func_has_Paci ON Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id WHERE usuarios.sexo = 'f' AND  Funcionarios.usuarios_id  = ".Session::get("ID"));
$homem = $stmt->selectManager("SELECT * FROM Anamnese INNER JOIN Paciente ON Paciente.id = Anamnese.Paciente_id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id INNER JOIN Func_has_Paci ON Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id WHERE usuarios.sexo = 'm' AND  Funcionarios.usuarios_id  = ".Session::get("ID"));


$allPaciente[0] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 0+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[1] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 1+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[2] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 2+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[3] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 3+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[4] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 4+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[5] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 5+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[6] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 6+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[7] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 7+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[8] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 8+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[9] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 9+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[10] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 10+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$allPaciente[11] = $stmt->selectManager("SELECT DATE_FORMAT(Func_has_Paci.start, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.start, '%m') = 11+1 AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));

$pacientesAtendidos[0] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 0+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[1] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 1+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[2] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 2+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[3] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 3+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[4] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 4+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[5] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 5+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[6] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 6+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[7] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 7+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[8] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 8+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[9] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 9+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[10] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 10+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));
$pacientesAtendidos[11] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 11+1  AND Funcionarios.usuarios_id = " . \Ballybran\Helpers\Security\Session::get("ID"));

$pacientes =  $stmt->selectManager("SELECT Func_has_Paci.*, Paciente.*, Func_has_Paci.* , usuarios.* FROM Func_has_Paci INNER JOIN Paciente INNER JOIN Funcionarios ON Func_has_Paci.Funcionarios_id = Funcionarios.id AND Func_has_Paci.Paciente_id = Paciente.id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and Funcionarios.usuarios_id =".\Ballybran\Helpers\Security\Session::get('ID') );

?>




<div class="col-lg-12 col-sm-12">
    <div class="row ">
            <div class="col-lg-3 ">

                <?php if (!empty($this->UserPhoto['path'])) { ?>

                    <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7  img-responsive img-circle" alt="<?php echo $this->UserPhoto['name']; ?>" />
                            <?php

                        } else {?>
                            <img  src="<?php echo URL . DIR_FILE?>Public/images/profile-icon.png" class="col-lg-7  img-responsive img-circle" />
                        <?php } ?>
            </div>

            <div class="col-lg-3  text-left">
                <h4>Contacto</h4>

                <strong>Nome: </strong><?php echo  $this->user['firstname'] . "\t" .  $this->user['lastname']; ?><br>
                <strong>Telefone: </strong><?php echo  $this->user['telephone']; ?><br>
                <strong>Email: </strong><?php echo  $this->user['email']; ?><br>

            </div>

            <div class="col-lg-3  text-left">
                <h4>Outras</h4>
                <strong>Sexo: </strong><?php echo  $this->user['sexo'] == 'f' ? "Feminino" : "Masculino"; ?><br>
                <strong>Aniversário: </strong><?php echo  $this->user['dataNascimento']; ?><br>
                <strong>Perfil: </strong><?php echo  $this->user['role']; ?><br>

            </div>
            <div class="col-lg-3  text-left">
                <h4>Endereço</h4>

                <strong>Endereço 1: </strong><?php echo  $this->user['address_1'] ?><br>
                <strong>Endereço 2: </strong><?php echo  $this->user['address_2']; ?><br>
                <strong>Cidade: </strong><?php echo  $this->user['city']; ?><br>
                <strong>País: </strong><?php echo  $this->user['country']; ?><br>
            </div>

    </div>
</div>

            <div class="col-lg-12 col-sm-12">
                <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
                    <div class="btn-group" role="group">
                        <div  id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                            <div class="hidden-xs">Painel</div>
                        </div>
                    </div>
                    <div class="btn-group" role="group">
                        <div  id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="icon icon fa-user" aria-hidden="true"></span>
                            <div class="hidden-xs">Pacientes</div>
                        </div>
                    </div>
                    <div class="btn-group" role="group">
                        <div  id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            <div class="hidden-xs">Consultas Feitas</div>
                        </div>
                    </div>
                    <div class="btn-group" role="group">
                        <div  id="stars" class="btn btn-default" href="#tab4" data-toggle="tab"><span class="icon icon fa-cog" aria-hidden="true"></span>
                            <div class="hidden-xs">Configurações</div>
                        </div>
                    </div>
                    <div class="btn-group" role="group">
                        <div  id="agenda" class="btn btn-default" href="#tab5" data-toggle="tab"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                            <div class="hidden-xs">Agenda</div>
                        </div>
                    </div>

                </div>

                <div class="panel panel-info col-lg-12">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">
                            <br><br>
                            <!--- blocos de contagem-->
                            <div class="row">


                                <div class="col-lg-2 col-sm-6">
                                    <div class="circle-tile ">
                                        <a href="#"><div class="circle-tile-heading dark-orange"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                        <div class="circle-tile-content dark-orange">
                                            <div class="circle-tile-description text-faded"> Agendados </div>
                                            <div class="circle-tile-number text-faded "><?php echo count($agendados);?></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-sm-6">
                                    <div class="circle-tile ">
                                        <a href="#"><div class="circle-tile-heading dark-red"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                        <div class="circle-tile-content dark-red">
                                            <div class="circle-tile-description text-faded"> Atendidos </div>
                                            <div class="circle-tile-number text-faded "><?php echo count($atendido);?></div>
                                        </div>
                                    </div>
                                </div>

                                  <div class="col-lg-2 col-sm-6">
                                    <div class="circle-tile ">
                                        <a href="#"><div class="circle-tile-heading dark-blue-dark"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                        <div class="circle-tile-content dark-blue-dark">
                                            <div class="circle-tile-description text-faded"> faltaram </div>
                                            <div class="circle-tile-number text-faded "><?php echo count($faltaram);?></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row ">


                                <div class="col-lg-4 u4 12u(mobile)">
                                    <div class="card">

                                        <div class="header">
                                            <h4 class="titles">Estatisticas de Paciente</h4>
                                        </div>
                                        <div class="content">

                                            <canvas id="barChart"   width="600" height="400"></canvas>

                                            <div class="footer">
<!--                                                 <canvas id="barSexo1"  width="600" height="400"></canvas>
 -->
                                                <hr>
                                            </div>
                                        </div>
                                    </div>
                                </div> <!-- end -->

                                <div class="col-lg-4 u4 12u(mobile)">
                                    <div class="card">

                                        <div class="header">
                                            <h4 class="titles">Estatisticas de Paciente Por Sexo</h4>
                                        </div>
                                        <div class="content">

                                            <canvas id="barSexo"  width="600" height="400"></canvas>

                                            <div class="footer">
                                                <hr>
                                            </div>
                                        </div>
                                    </div>
                                </div> <!-- end -->

                                <div class="col-lg-12">
                                    <div class="card">

                                        <div class="header">
                                            <h4 class="titles">Estatisticas Anual de Paciente</h4>
                                        </div>
                                        <div class="content">
                                            <canvas id="totalPaciente" class="ct-chart"></canvas>

                                            <div class="footer">
                                                <div class="legend">
                                                </div>
                                                <hr>
                                            </div>
                                        </div>
                                    </div>
                                </div> <!-- end -->


                               <!--  <div class="col-lg-11">
                                    <div class="card ">
                                        <div class="header">
                                            <h4 class="titles">2014 Sales</h4>
                                            <p class="category">All products including Taxes</p>
                                        </div>
                                        <div class="content">
                                            <div id="chartActivity" class="ct-chart"></div>

                                            <div class="footer">
                                                <hr>
                                                <div class="stats">
                                                    <i class="fa fa-check"></i> Data information certified
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div> --> <!-- end -->

                            </div>
                        </div>

                        <div class="tab-pane fade in" id="tab2">
                            <br>

                            <div class="row" style="min-height:300px;">
                                <div class="col-lg-12 ">

                                    <div class="col-xs-8">
                                        <!-- required for floating -->
                                        <!-- Nav tabs -->
                                        <ul class="nav nav-tabs tabs-left">
                                            <li class="active"><a href="#ListPaci" data-toggle="tab">Lista  de Pacientes</a></li>
                                            <li><a href="#addPaci" data-toggle="tab" class="glyphicon glyphicon-user ">Novo Paciente</a></li>

                                        </ul>
                                    </div>
                                    <div class="col-xs-12">
                                        <!-- Tab panes -->
                                        <div class="tab-content">
                                            <div class="tab-pane active" id="ListPaci">
                                                <a href="<?php echo URL;?>account/printListPacienteForConsult" class="btn btn-success" target="_blank">Imprimir Lista</a>


                                            <div id="pacilistFalta">
                                                <input type="text" class="search form-control" placeholder="Search Paciente"  />
                                                <table class="table table-bordered">
                                                    <thead>
                                                    <tr>
                                                        <th class="sort" data-sort="name1">Name </th>
                                                        <th class="sort" data-sort="date1">Info</th>
                                                        <th class="sort" data-sort="hora1">Data agendada</th>
                                                        <th class="sort" data-sort="hora1"></th>
                                                    </tr>
                                                    </thead>
                                                    <tbody class="list">

                                                    <?php foreach ($this->paciente as $key => $value) :?>

                                                             <tr>
                                                            <td class="id" style="display:none;"><?php echo $key['id']+1;?></td>
                                                            <td class="name1"><?php echo $value['firstname'] . "\t" .  $value['lastname'];?></td>
                                                            <td class="date1"><?php echo $value['info'];?></td>
                                                            <td class="hora1"><?php echo $value['start'];?></td>
                                                            <td ><a href="<?php echo URL; ?>funcionario/prontuario/<?php echo $value['id'];?>"> Atender</a></td>
                                                        </tr>

                                                    <?php  endforeach; ?>

                                                    </tbody>
                                                </table>
                                            </div>
                                            </div>


                                            <div class="tab-pane" id="addPaci">

                                                <?php
                                                echo Form::open(['method' => 'post', 'action' => URL . 'User/signUp', 'files' => 'enctype=multipart/form-data', 'name' => 'signUp', 'class' => 'form-signin', 'style' => 'width:60%;']);
                                                ?>

                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Nome</label>
                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'firstname', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Nome Completo']);
                                                    ?>
                                                </div>

                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Sobrenome</label>
                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'lastname', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Nome Completo']);
                                                    ?>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Username</label>

                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'username', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'user name']);
                                                    ?>

                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Email</label>

                                                    <?php
                                                    echo Form::input(['type' => 'email', 'name' => 'email', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'email']);
                                                    ?>

                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Password</label>

                                                    <?php
                                                    echo Form::input(['type' => 'password', 'name' => 'password', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Password']);
                                                    ?>
                                                </div>

                                                <?php
                                                echo Form::button(['type' => 'submit', 'class' => 'form-button-submit button', 'id' => 'send_request', 'value' => 'Cadastrar']);
                                                ?>

                                                <?php
                                                echo Form::close();
                                                ?>

                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>

                        </div>
                        <div class="tab-pane fade in" id="tab3">
                            <br>

                            <div class="row" style="min-height:300px;">
                                <div  class="col-sm-12">
                                    <div class="col-xs-6">
                                        <!-- required for floating -->
                                        <!-- Nav tabs -->
                                        <ul class="nav nav-tabs tabs-left">
                                            <li class="active"><a href="#func" data-toggle="tab">Lista  de Paciente</a></li>
                                            <li><a href="#faltas" data-toggle="tab">Pacientes que Faltaram</a></li>

                                        </ul>
                                    </div>
                                    <div class="col-xs-12">
                                        <!-- Tab panes -->
                                        <div class="tab-content">
                                            <div class="tab-pane active" id="func">



                                                <ul class="list-group" id="contact-list">


                                                        <div id="pacilistPagamento">
                                                            <input type="text" class="search form-control" placeholder="Search Paciente"  />
                                                            <table class="table table-bordered">
                                                                <thead>
                                                                <tr>
                                                                    <th class="sort" data-sort="name1">Name </th>
                                                                    <th class="sort" data-sort="aria1">Especialidade</th>
                                                                    <th class="sort" data-sort="medico1">Ver Atendimento</th>
                                                                </tr>
                                                                </thead>
                                                                <tbody class="list">

                                                                <?php foreach ($this->atendidos as $key => $value) :?>

                                                                    <tr>
                                                                        <td class="id1" style="display:none;"><?php echo $key['id']+1;?></td>
                                                                        <td class="name1"><?php echo $value['firstname'] . "\t" .  $value['lastname'];?></td>
                                                                        <td class="aria1"><?php echo $value['aria'];?></td>
                                                                        <td class="medico1"><!--<a href="" data-toggle="modal" data-target="#exampleModalLongReceita-<?php echo $value['id'];?>"> Ver Atendimento</a> -->
                                                                            <a  class="btn btn-success" target="_blank" href="<?php echo URL ;?>account/printProntuario/<?php echo $value['id'];?>"> print prontuario</a>
                                                                            <a class="btn btn-success" target="_blank" href="<?php echo URL;?>account/printPrescricao/<?php echo $value['id'];?>"> print Receita</a>
                                                                        </td>



                                                                        <!-- Modal 1 -->
                                                                        <div class="modal fade col-lg-12" id="exampleModalLongReceita-<?php echo $value['id'];?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                                                                            <div class="modal-dialog modal-lg" role="document">
                                                                                <div class="modal-content">
                                                                                    <div class="modal-header">
                                                                                        <h5 class="modal-title" id="exampleModalLongTitle">Consulta do Pacienet:  </h5>
                                                                                        <small><?php echo $value['firstname'] . "\t" . $value['lastname'];?></small>

                                                                                        <footer>
                                                                                            <div class="footer" id="footer">
                                                                                                <div class="row">
                                                                                                    <div class="col-lg-6 ">

                                                                                                        <?php   $this->prontuario = $stmt->selectManager(" SELECT * FROM Paciente INNER JOIN usuarios ON usuarios.id= Paciente.usuarios_id
                                                                    INNER JOIN Func_has_Paci ON Func_has_Paci.Paciente_id = Paciente.id
                                                                    INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id
                                                                    LEFT OUTER JOIN Convenio ON Convenio.id = Paciente.Convenio_id
                                                                    LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id
                                                                    LEFT OUTER JOIN Docum_Atestado ON Docum_Atestado.Paciente_id = Paciente.id
                                                                    LEFT OUTER JOIN Evolucao ON Evolucao.Paciente_id = Paciente.id
                                                                    LEFT OUTER JOIN Exame_Fisico ON Exame_Fisico.Paciente_id = Paciente.id
                                                                    LEFT OUTER JOIN hipotese_diagnostica ON hipotese_diagnostica.Paciente_id = Paciente.id
                                                                    LEFT OUTER JOIN Medicamento ON Medicamento.Paciente_id = Paciente.id WHERE Paciente.id =". $value['id'] )[0];?>

                                                                                                        <h3> Dados Pessoais</h3>
                                                                                                        <strong>Nome:</strong> <strong><small><?php echo $this->prontuario['firstname']. "\t" .$this->prontuario['lastname'] ;?></small></strong><br>
                                                                                                        <strong>Sexo:</strong> <strong><small> <?php echo $this->prontuario['sexo'];?></small></strong><br>
                                                                                                        <strong>Telefone1</strong> <strong><small> <?php echo $this->prontuario['telephone'];?></small></strong><br>
                                                                                                        <strong>Celular:</strong> <strong><small> <?php echo $this->prontuario['telephone2'];?></small></strong><br>
                                                                                                        <strong>E-mail:</strong> <strong><small> <?php echo $this->prontuario['email'];?></small></strong><br>
                                                                                                        <strong>C.Postal:</strong> <strong><small> <?php echo $this->prontuario['postcode'];?></small></strong><br>
                                                                                                        <strong>Endereço:</strong> <strong><small> <?php echo $this->prontuario['address_1'];?></small></strong><br>
                                                                                                        <strong>Número:</strong> <strong><small> <?php echo $this->prontuario['address_2'];?></small></strong><br>
                                                                                                        <strong>Bairro:</strong> <strong><small> <?php echo $this->prontuario['bairro'];?></small></strong><br>
                                                                                                        <strong>Cidade:</strong> <strong><small> <?php echo $this->prontuario['city'];?></small></strong><br>
                                                                                                        <strong>Estado:</strong> <strong><small> <?php echo $this->prontuario['states'];?></small></strong><br>
                                                                                                        <strong>Paciente Cadastrado em:</strong> <strong><small> <?php echo $this->prontuario['create_dt'];?></small></strong><br>
                                                                                                        <strong>Última Consulta:</strong> <strong><small> <?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                        <strong>Numero de Consulta: </strong> <strong><small><?php echo $this->prontuario['id'];?></small></strong><br>
                                                                                                        <h3> Annaminese</h3>

                                                                                                        <?php echo $this->prontuario['queixa_pri'] != "" ? "<strong>Qiexa Principal:</strong> <strong><small> {$this->prontuario['queixa_pri']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['historia'] != "" ? "<strong>História:</strong> <strong><small> {$this->prontuario['historia']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['prob_renais'] != "" ? "<strong>Problemas Renais:</strong> <strong><small> {$this->prontuario['prob_renais']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['prob_artic_reum'] != "" ? "<strong>Problemas articulares ou reumatismo:</strong> <strong><small> {$this->prontuario['prob_artic_reum']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['prob_cardiaco'] != "" ? "<strong>Próblemas Cardiacos:</strong> <strong><small> {$this->prontuario['prob_cardiaco']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['prob_respira'] != "" ? "<strong>Problemas Respiratórios:</strong> <strong><small> {$this->prontuario['prob_respira']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['prob_gastricos'] != "" ? "<strong>Próblemas Gastrícos:</strong> <strong><small> {$this->prontuario['prob_gastricos']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['alergia'] != "" ? "<strong>Alergia:</strong> <strong><small> {$this->prontuario['alergia']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['hepatite'] != "" ? "<strong>Hepatite:</strong> <strong><small> {$this->prontuario['hepatite']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['gravides'] != "" ? "<strong>Gravides:</strong> <strong><small> {$this->prontuario['gravides']}</small></strong><br>" : ""?>
                                                                                                        <?php echo $this->prontuario['uso_de_medicam'] != "" ? "<strong>Uso de Medicamento:</strong> <strong><small> {$this->prontuario['uso_de_medicam']}</small></strong><br>" : ""?>

                                                                                                    </div>
                                                                                                    <div class="col-lg-6 ">
                                                                                                        <h3> Dados Complementares </h3>
                                                                                                        <strong>Naturalidade:</strong> <strong><small><?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                        <strong>Etnia:</strong> <strong><small> <?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                        <strong>Estado Cívil:</strong> <strong><small> <?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                        <strong>Profissão:</strong> <strong><small> <?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                        <strong>E-mail:</strong> <strong><small> <?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                        <strong>Excolaridade:</strong> <strong><small> <?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                        
                                                                                                        <h3>Convenio</h3>
                                                                                                        <strong>Plano:</strong> <strong><small> <?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                        <strong>Data de vencimento:</strong> <strong><small> <?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                        <strong>Acomodação:</strong> <strong><small> <?php echo $this->prontuario['firstname'];?></small></strong><br>
                                                                                                    </div>

                                                                                                </div>
                                                                                                <!--/.container-->
                                                                                            </div>
                                                                                            <!--/.footer-->


                                                                                        </footer>
                                                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                                            <span aria-hidden="true">&times;</span>
                                                                                        </button>
                                                                                    </div>
                                                                                    <div class="modal-body">

                                                                                    </div>
                                                                                    <div class="modal-footer">

                                                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                                                                        <?php  echo Form::button(['type'=> 'button', 'value'=> 'Impimir']);
                                                                                        echo Form::close();
                                                                                        ?>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div> <!-- modal 1 end -->
                                                                    </tr>
                                                                    <?php endforeach; ?>


                                                                </tbody>
                                                            </table>


                                                        </div>



                                                            <div class="clearfix"></div>

                                                </ul>
                                            </div>


                                            <!--- -->
                                            <div class="tab-pane " id="faltas">

                                                <div id="pacilistFalta">
                                                    <input type="text" class="search form-control" placeholder="Search Paciente"  />
                                                    <table class="table table-bordered">
                                                        <thead>
                                                        <tr>
                                                            <th class="sort" data-sort="name2">Name </th>
                                                            <th class="sort" data-sort="aria2">Especialidade</th>
                                                            <th class="sort" data-sort="hora2">Data agendada</th>
                                                            <th class="sort" data-sort="date2">Dia da consulta</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody class="list">

                                                        <?php foreach ($faltaram as $item => $allPacientes) {?>
                                                            <tr>
                                                                <td class="id2" style="display:none;"><?php echo $item['id']+1;?></td>
                                                                <td class="name2"><?php echo $allPacientes['firstname'] . "\t" .  $allPacientes['lastname'];?></td>
                                                                <td class="aria2"><?php echo $allPacientes['aria'];?></td>
                                                                <td class="hora2"><?php echo $allPacientes['create_dt'];?></td>
                                                                <td class="date2"><?php echo $allPacientes['Func_dt'];?></td>
                                                            </tr>
                                                        <?php } ?>

                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div> <!-- -->

                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade in" id="tab4">

                            <div class="row" style="min-height:300px;">
                                <div  class="col-lg-12">
                                    <div class="col-xs-8">
                                        <!-- required for floating -->
                                        <!-- Nav tabs -->
                                        <ul class="nav nav-tabs tabs-left">
                                            <li class="active"><a href="#home" data-toggle="tab">Dados Pessoais</a></li>
                                            <li><a href="#info" data-toggle="tab">Atualizar dados</a></li>
                                            <li><a href="#password" data-toggle="tab">Password</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-xs-9">
                                        <!-- Tab panes -->
                                        <div class="tab-content">
                                            <div class="tab-pane active" id="home">
                                                <br><br><br>

                                                <div class="row">

                                                    <div class="panel panel-info col-lg-12" >
                                                        <div class="panel-heading">
                                                            <h3 class="panel-title">Meus Dados</h3>
                                                        </div>
                                                        <div class="panel-body">
                                                            <div class="row">

                                                                <div class=" col-md-9 col-lg-9 ">
                                                                    <div class="col-lg-7 ">

                                                                        <?php if (!empty($this->UserPhoto['path'])) { ?>

                                                                            <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7 image img-responsive img-thumbnail" alt="<?php echo $this->UserPhoto['name']; ?>" />
                                                                            <?php
                                                                            if (Session::exist()) {
                                                                                ?>
                                                                                <a href="<?php echo URL; ?>account/deleteImage"  class="glyphicon glyphicon-remove" >delete</a>
                                                                                <?php

                                                                            }
                                                                        } else {?>
                                                                            <img  src="<?php echo URL . DIR_FILE?>Public/images/profile-icon.png" class="col-lg-7  img-responsive img-circle"  />
                                                                        <?php } ?>
                                                                    </div>
                                                                    <br>
                                                                    <table class="table table-user-information">
                                                                        <tbody>
                                                                        <tr>
                                                                            <td>Especialidade:</td>
                                                                            <td><?php echo $this->user['telephone'];?></td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>Contratado em::</td>
                                                                            <td><?php echo $this->user['create_time'];?></td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>Data de Nascimento</td>
                                                                            <td><?php echo $this->user['dataNascimento'];?></td>
                                                                        </tr>

                                                                        <tr>
                                                                        <tr>
                                                                            <td>Genero</td>

                                                                            <td>
                                                                                <?php  echo $this->user['sexo'] != "" ?  $this->user['sexo'] == 'f' ? "Feminino" : "Masculino" : NULL;?>
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>Endereço</td>
                                                                            <td><?php echo $this->user['address_1'];?></td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>Email</td>
                                                                            <td><a href="mailto:<?php echo $this->user['email'];?>"><?php echo $this->user['email'];?></a></td>
                                                                        </tr>
                                                                        <td>Numero do Telefone</td>
                                                                        <td><?php echo $this->user['telephone'];?><br><br><?php echo $this->user['telephone2'];?>(Mobile)
                                                                        </td>

                                                                        </tr>

                                                                        </tbody>
                                                                    </table>

                                                                </div>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>
                                                <!-- profile end -->

                                            </div>
                                            <div class="tab-pane" id="info">
                                                <br><br>
                                                <form method="post" action="<?php echo URL; ?>account/insertImageUser" enctype="multipart/form-data">
                                            <label for="pic">Faça o Uploads de uma foto para o perfil:</label>
                                            <input type="file" name="archive[]" id="pic" />
                                            <label for="colorWell">Qualidade:</label>
                                            <input type="number" value="50" name="quality"/>
                                            <label for="colorWell">Rotação:</label>
                                            <input type="number"  value="00" name="degree" />
                                            <label for="colorWell">Color:</label>
                                            <input type="color" name="color" value="#ff0000" class="contact-form" id="colorWell" />
                                            <input type="submit" value="Carregar" />
                                        </form>


                                                <h4>My Account</h4>


                                                <?php
                                                echo Form::open(['method' => 'post', 'action'=> URL .'account/updates', 'name' => '', 'class' => 'form-signin', 'style' => 'width:50%']);
                                                ?>

                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">First Name</label>
                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'firstname', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['firstname']]);
                                                    ?>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Last Name</label>
                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'lastname', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['lastname']]);
                                                    ?>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">User Name</label>

                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'username', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['username']]);
                                                    ?>

                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">E-mail</label>

                                                    <?php
                                                    echo Form::input(['type' => 'email', 'name' => 'email', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['email']]);
                                                    ?>

                                                </div>
                                                <small>Your Address</small>
                                                <hr>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Telephone</label>
                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'telephone', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['telephone']]);
                                                    ?>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Company</label>
                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'company', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['company']]);
                                                    ?>
                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Address 1</label>

                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'address_1', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['address_1']]);
                                                    ?>

                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Address 2</label>

                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'address_2', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['address_2']]);
                                                    ?>

                                                </div>
                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Post Code</label>

                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'postcode', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['postcode']]);
                                                    ?>
                                                </div>

                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">City</label>

                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'city', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['city']]);
                                                    ?>
                                                </div>

                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Country</label>

                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'country', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['country']]);
                                                    ?>
                                                </div>

                                                <div class="form-group">
                                                    <label class="control-label" for="input-firstname">Region/State</label>

                                                    <?php
                                                    echo Form::input(['type' => 'text', 'name' => 'zone', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['zone']]);
                                                    ?>

                                                </div>
                                                <?php
                                                echo Form::input(['type' => 'hidden', 'name' => 'id', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['id']]);
                                                ?>


                                                <div class="form-group">
                                                    <br/>
                                                    <button class="btn btn-primary btn-inverse btn-default" onclick="updateUser(<?php echo $this->user['id']; ?>)" ><p class="glyphicon glyphicon-refresh "></p></button>
                                                    <a class="btn btn-danger deletar" href="<?php echo URL ?>account/deletes/<?php echo $this->user['id']; ?>"><p class="glyphicon glyphicon-trash "></p></a>

                                                </div>

                                                <?php
                                                echo Form::close();
                                                ?>
                                            </div>
                                            <div class="tab-pane" id="password">
                                                <br><br>
                                                <section>

                                                    <div class="row">
                                                        <form  class="form-horizontal" action="<?php echo URL; ?>account/managePassword" name="perfil" method="post">

                                                            <div class="form-group">
                                                                <label for="exampleInputPassword1">Password</label>
                                                                <input type="password" class="form-control" placeholder="Senha antiga" name="password2" id="exampleInputPassword1">
                                                                <br>
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="exampleInputPassword1">Password</label>
                                                                <input type="password" class="form-control" placeholder="Senha Nova" name="password" id="exampleInputPassword1">
                                                                <input type="hidden" class="form-control" name="id" value="<?php echo $this->user['id']; ?>"  id="exampleInputPassword1">
                                                                <br>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <button type="submit" class="btn btn-info">Atualizar</button>
                                                            </div>

                                                        </form>
                                                    </div>
                                                </section>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade in" id="tab5">

                            <br><br>
                            <div class="col-md-12">
                                    <div class="header">
                                        <div id="calendar"></div>


                                        <!-- Modal -->
                                        <div id="createEventModal" class="modal fade" role="dialog">
                                            <div class="modal-dialog">

                                                <!-- Modal content-->
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                        <h4 class="modal-title">Add Event</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <div class="control-group">
                                                            <label class="control-label" for="inputPatient">Event:</label>
                                                            <div class="field desc">
                                                                <input class="form-control" id="title" name="title" placeholder="Event" type="text" value="">
                                                            </div>
                                                        </div>

                                                        <input type="hidden" id="startTime"/>
                                                        <input type="hidden" id="endTime"/>



                                                        <div class="control-group">
                                                            <label class="control-label" for="when">When:</label>
                                                            <div class="controls controls-row" id="when" style="margin-top:5px;">
                                                            </div>
                                                        </div>

                                                    </div>
                                                    <div class="modal-footer">
                                                        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                                                        <button type="submit" class="btn btn-primary" id="submitButton">Save</button>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>


                                        <div id="calendarModal" class="modal fade">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                        <h4 class="modal-title">Event Details</h4>
                                                    </div>
                                                    <div id="modalBody" class="modal-body">
                                                        <h4 id="modalTitle" class="modal-title"></h4>
                                                        <div id="modalWhen" style="margin-top:5px;"></div>
                                                    </div>
                                                    <input type="hidden" id="eventID"/>
                                                    <div class="modal-footer">
                                                        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                                                        <button type="submit" class="btn btn-danger" id="deleteButton">Delete</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Modal-->

                                    </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
</div>



    <script>

    var PieChart = {
        type : "pie",
        data : {
            datasets: [{
                data :
                    [
                        [<?php echo json_encode(count($agendados));?>],
                        [<?php echo json_encode(count($atendido));?>],
                        [<?php echo json_encode(count($faltaram));?>]


                    ],

                backgroundColor: [
                                        "#FDB45C",
                    "#f7464a",
                    "#1d38d3"
                ]
            }],
            labels :


                [
                    ' Agendados',
                    'Atendidos',
                    'Faltaram'
                ]

        },

        options : {
            responsive : true
        }
    };
    var pie = document.getElementById('barChart').getContext('2d');
    window.line = new Chart(pie, PieChart);


    var PieChartSexo = {
        type : "pie",
        data : {
            datasets: [{
                data :
                    [
                        [<?php echo json_encode(count($mulher));?>],
                        [<?php echo json_encode(count($homem));?>]


                    ],

                backgroundColor: [
                    "#f7409e",
                    "#1DC7EA"

                ]
            }],
            labels :


                [
                    ' Mulher',
                    'Homem'
                ]

        },

        options : {
            responsive : true
        }
    };
    var pies = document.getElementById('barSexo').getContext('2d');
    window.line = new Chart(pies, PieChartSexo);

    //
    var ctx = document.getElementById("totalPaciente").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "julho", "Agosto", "Setembro", "Outrubto", "Noembro", "Dezembro"],
            datasets: [

                {
                    label: 'Pacientes Agendados',
                    data: [

                        <?php echo json_encode(count($allPaciente[0]));?>,
                        <?php echo json_encode(count($allPaciente[1]));?>,
                        <?php echo json_encode(count($allPaciente[2]));?>,
                        <?php echo json_encode(count($allPaciente[3]));?>,
                        <?php echo json_encode(count($allPaciente[4]));?>,
                        <?php echo json_encode(count($allPaciente[5]));?>,
                        <?php echo json_encode(count($allPaciente[6]));?>,
                        <?php echo json_encode(count($allPaciente[7]));?>,
                        <?php echo json_encode(count($allPaciente[8]));?>,
                        <?php echo json_encode(count($allPaciente[9]));?>,
                        <?php echo json_encode(count($allPaciente[10]));?>,
                        <?php echo json_encode(count($allPaciente[11]));?>
                        ],
                        
                        backgroundColor: [
                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E"
                    ],
                    borderColor: [

                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E",
                        "#34495E"
                    ],
                   
                    borderWidth: 1
                },
                {
                    label: 'Atendidos',
                    data: [
                        <?php echo json_encode(count($pacientesAtendidos[0]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[1]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[2]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[3]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[4]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[5]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[6]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[7]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[8]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[9]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[10]))?>,
                        <?php echo json_encode(count($pacientesAtendidos[11]))?>
                        ],

                         backgroundColor: [
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a"

                    ],
                    borderColor: [
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a",
                        "#f7464a"
                    ],

                    borderWidth: 1
                }]
        },
        scales: {
            yAxes: [{
                barPercentage: 0.5
            }]
        },
        elements: {
            rectangle: {
                borderSkipped: 'left'
            }
        }
    });

</script>

<script>


    $(document).ready(function() {

        var localeCode = "pt-br";

        $.post( '<?php echo URL;?>account/event',
            function(data){
//                alert(data)

                $('#calendar').fullCalendar({
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,agendaWeek,agendaDay'
                    },
                    buttonText: {
                        today:    'Hoje',
                        month:    'Mês',
                        week:     'Semana',
                        day:      'Dia'
                    },
                    theme: true,
                    themeSystem:'bootstrap3',
                    locale: localeCode,
                    defaultDate: new Date(),
                    navLinks: true, // can click day/week names to navigate views
                    editable: true,
                    selectable: true,
                    selectHelper: true,
                    allDaySlot: true,
//                    eventLimit: false, // allow "more" link when too many events
                    events: $.parseJSON(data),
//                    eventColor: '#378006',
                    eventDrop: function(event, delta, revertFunc){

                        var newId = event.id;
                        var newStard =$.fullCalendar.moment(event.start).format();
                        var newEnd = $.fullCalendar.moment(event.end).format();
                        var newTitle = event.title;

                        if (!confirm("Esta seguro??")) {
                            revertFunc();
                        }else{
                            $.post('<?php echo URL;?>Events/updatEvent',
                                {
                                    id:newId,
                                    start:newStard,
                                    end:newEnd,
                                    title:newTitle
                                },
                                function(data){
                                    if (data == 1) {
                                        alert('Se actualizo correctamente');
                                    }
                                });
                        }
                    },
                    eventResize: function(event, delta, revertFunc) {
                        var newId = event.id;
                        var newStard =$.fullCalendar.moment(event.start).format();
                        var newEnd = $.fullCalendar.moment(event.end).format();
                        var newTitle = "Consulta";



                        if (!confirm("Esta seguro de cambiar la fecha?")) {
                            revertFunc();
                        }else{
                            $.post('<?php echo URL;?>Events/updatEvent',
                                {
                                    id:newId,
                                    start:newStard,
                                    end:newEnd,
                                    title:newTitle

                                },
                                function(data){
                                    if (data == 1) {
                                        alert('Se cambio correctamente');
                                    }
                                });
                        }
                    },
                    eventClick: function(event, jsEvent, view) {

                        if(event.sexo == "f") {

                            $('#sexo').html("Feminino");
                        }else{

                            $('#sexo').html("Masculino");
                        }


                        if(event.path == null) {
                        document.getElementById("imagePerfil").src ='<?php echo URL . DIR_FILE?>Public/images/profile-icon.png';
                        } else{
                        document.getElementById("imagePerfil").src ='<?php echo URL;?>'+ event.path;

                        }

                        $('#mhdnIdEvento').val(event.id);
                        $('#title').val(event.title);
                        $('#nome').html(event.firstname + " " + event.lastname);
                        $('#telefone').html(event.telephone);
                        $('#address_1').html(event.address_1);
                        $('#address_2').html(event.address_2);
                        $('#bairro').html(event.bairro);
                        $('#city').html(event.city);
                        $('#email').html(event.email);
                        $('#infos').html(event.info);
                        $('#Peciente_id').html(event.Paciente_id);
                        $('#modalEvento').modal();

                        if (event.url) {
                            window.open(event.id);
                            return false;
                        }

                    },

                    eventAfterRender: function (event, element, view) {
                        var dataHoje = new Date();
                        if (event.start < dataHoje && event.end > dataHoje) {
                            //event.color = "#FFB347"; //Em andamento
                            element.css('background-color', '#FFB347');
                            } else if (event.start < dataHoje && event.end < dataHoje) {
                            //event.color = "#77DD77"; //Concluído OK
                            element.css('background-color', '#77DD77');
                        } else if (event.start > dataHoje ) {
                            //event.color = "#AEC6CF"; //Não iniciado
                            element.css('background-color', '#AEC6CF');
                        }
                    },

                    eventRender: function(event, element) {
                        var el = element.html();
                        element.html("<div style='width:90%;float:left;'>" + el + "</div>" +
                            "<div style='color:red;text-align:right;' class='closeE'>" +
                            "<i class='fa fa-trash'></i>" +
                            "</div>");

                        element.find('.closeE').click(function(){
                            if (!confirm("Esta seguro de eliminar el evento?")) {
                                return false;
                            }else{
                                var id = event.Paciente_id;

                                $.post('<?php echo URL;?>Events/deleteEvent',
                                    {
                                        Paciente_id:id
                                    },
                                    function(data){
                                        if (data === 1) {
                                            $('#calendar').fullCalendar( 'removeEvents', event.Paciente_id);
                                            alert('Se elimino correctamente');
                                        }
                                    });

                            }

                        });
                    }

                });
            });



    });

</script>


<!-- Modal Cierre -->
<div class="modal fade " id="modalEvento" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Marcar Consulta</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="col-lg-12 card-radius">

                                <div class="col-lg-3 ">

                    <img   id="imagePerfil"  class="col-lg-10  img-responsive img-circle" />
                
                  
            </div>

                    <div class="col-lg-3  text-left">
                        <h4>Contacto</h4>

                        <strong>Nome: </strong><small id="nome"></small><br>
                        <strong>Telefone: </strong><small id="telefone"></small><br>
                        <strong>Email: </strong><small id="email"></small><br>

                    </div>

                    <div class="col-lg-3  text-left">
                        <h4>Outras</h4>
                        <strong>Sexo: </strong><small id="sexo"></small><br>
                        <strong>Aniversário: </strong><small id="nome"></small><br>

                    </div>
                    <div class="col-lg-3  text-left">
                        <h4>Endereço</h4>

                        <strong>Endereço 1: </strong><small id="address_1"></small><br>
                        <strong>Endereço 2: </strong><small id="address_2"></small><br>
                        <strong>Cidade: </strong><small id="city"></small><br>
                        <strong>País: </strong><small id="bairro"></small><br>
                        <strong>Numero: </strong><small id="Peciente_id"></small><br>
                    </div>
                </div>
                <textarea id="infos"  cols="141" aria-disabled="true" disabled></textarea>
        </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button class="hora1" onclick="doSubmit()"> Atender</button>
            </div>
        </div>
    </div>
</div>

<script>

    $('#btnUpdEvento').click(function(){
        var title = $('#title').val();
        var ide = $('#idTexte').val();

        $.post("<?php echo URL;?>account/updEvento2",
            {
                title: title,
                id: ide
            },
            function(data){
                if (data == 1) {
                    $('#btnCerrarModal').click();
                }
            });
    })
    var hi = $("#id").hide();
        function doSubmit(){
            var title = document.getElementById('id').innerHTML;

            document.location= "<?php echo  URL;?>funcionario/prontuario/" + title;

        }

    var options1 = {
        valueNames: [ 'id1', 'name1', 'aria1', 'medico1', ]
    };

    // Init list
    var consultListAgend = new List('pacilistPagamento', options1);


</script>
