<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

use Ballybran\Helpers\Security\Session;
use Module\menu\Sub_Menu;
use Ballybran\Library\Form;
Sub_Menu::getSubMenu();
?>


<div class="container" id="features" >
    <div class="breadcrumb text-center" id="features">
        <strong>Dados do Paciente</strong>

    </div>
    <div class="row ">

        <div class="col-lg-3 4u 12u(mobile)">

            <?php if (!empty($this->UserPhoto['path'])) { ?>

                <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7 image img-responsive img-thumbnail" alt="<?php echo $this->UserPhoto['name']; ?>" />
                <?php
                if (Session::exist()) {
                    ?>
                    <a href="<?php echo URL; ?>account/deleteImage"  class="glyphicon glyphicon-remove" >delete</a>
                    <?php

                }
            } else {
                echo "nao tem imagem";
            } ?>
        </div>

        <div class="col-lg-4 4u 12u(mobile) text-left">
            <h3>Contacto</h3>

            <?php foreach ($this->paciente as $kye => $value) : ?>
            <strong>Nome: </strong><?php echo  $value['firstname'] . "\t" .  $value['lastname']; ?><br>
            <strong>Telefone: </strong><?php echo  $value['telephone']; ?><br>
            <strong>Email: </strong><?php echo  $value['email']; ?><br>

        </div>

        <div class="col-lg-4 4u 12u(mobile) text-left">
            <h3>Endereço</h3>

            <strong>Endereço 1: </strong><?php echo  $value['address_1'] ?><br>
            <strong>Endereço 2: </strong><?php echo  $value['address_2']; ?><br>
            <strong>Cidade: </strong><?php echo  $value['city']; ?><br>
            <strong>País: </strong><?php echo  $value['country_id']; ?><br>
        </div>
        <?php endforeach; ?>

    </div>
</div>
<div class="container" id="features" >
    <div class="col-lg-12 4u 12u(mobile)">
        <div class="breadcrumb text-center" id="features">
            <strong>PRONTUÁRIO DO PACIENTE</strong>
        </div>

            <table class="table  table-black table-bordered table-responsive">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome do Paciente</th>
                    <th>Telefone</th>
                    <th>Infotmações</th>
                    <th>Hora Marcada para o Atendimento</th>
                    <th>Médico</th>
                    <th> Ver Prontuario</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->paciente as $key => $value) : ?>
                <tr>
                    <th scope="row"><?php echo $key + 1; ?></th>
                    <td><?php echo $value['firstname'] . "\t". $value['lastname'];?></td>
                    <td><?php echo $value['telephone'];?></td>
                    <td><?php echo $value['info'];?></td>
                    <td><?php echo $value['horas'];?></td>
                    <td><?php echo $value['titulo'];?></td>
                    <td><a href="<?php echo URL; ?>paciente/prontuario/<?php echo $value['Paciente_id'];?>"> <i class="glyphicon glyphicon-eye-open eye-white"></i></a></td>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>

    </div>
</div>


