<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */
use Ballybran\Helpers\Security\Session;
use Ballybran\Library\Form;

\Module\Clinic\Lib\menu\Sub_Menu::getSubMenu();
?>

<div class="text-center"><h1>RECEPÇÃO</h1></div>
<?php
$c = new \Ballybran\Core\Caller\Caller('Module\Lib\Visitor', 'contagem');
$d = $c->__init();

$register = \Ballybran\Database\RegistryDatabase::getInstance();
$stmt = $register->get("PDO");
$novos = $stmt->selectManager("SELECT * FROM usuarios LEFT OUTER JOIN Paciente ON usuarios.id = Paciente.usuarios_id WHERE Paciente.usuarios_id is null AND  usuarios.role = 'paciente' ");

$atendidos = $stmt->selectManager("SELECT * FROM Paciente INNER JOIN usuarios ON usuarios.id= Paciente.usuarios_id
                                                                    INNER JOIN Func_has_Paci ON Func_has_Paci.Paciente_id = Paciente.id
                                                                    INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id
                                                                    INNER JOIN Convenio ON Convenio.id = Paciente.Convenio_id 
                                                                    INNER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id AND Anamnese.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Docum_Atestado ON Docum_Atestado.Paciente_id = Paciente.id AND Docum_Atestado.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Evolucao ON Evolucao.Paciente_id = Paciente.id AND Evolucao.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Exame_Fisico ON Exame_Fisico.Paciente_id = Paciente.id AND Exame_Fisico.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN hipotese_diagnostica ON hipotese_diagnostica.Paciente_id = Paciente.id AND hipotese_diagnostica.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Medicamento ON Medicamento.Paciente_id = Paciente.id ");

$emEspera = $stmt->selectManager("SELECT  Paciente.*, Func_has_Paci.* FROM  Paciente LEFT OUTER JOIN Func_has_Paci on  Paciente.id = Func_has_Paci.Paciente_id WHERE Func_has_Paci.funcionarios_id is null");
$agendados = $stmt->selectManager(" SELECT * FROM Paciente LEFT OUTER JOIN Anamnese on Paciente.id = Anamnese.Paciente_id  INNER JOIN Func_has_Paci on  Paciente.id = Func_has_Paci.Paciente_id  WHERE  Anamnese.Paciente_id is null and Func_has_Paci.start > now()");
$faltaram = $stmt->selectManager(" SELECT * FROM Paciente LEFT OUTER JOIN Anamnese on Paciente.id = Anamnese.Paciente_id  INNER JOIN Func_has_Paci on  Paciente.id = Func_has_Paci.Paciente_id INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id WHERE  Func_has_Paci.start < now() AND Anamnese.Paciente_id is null ");

$mulher = $stmt->selectManager("SELECT * FROM Anamnese INNER JOIN Paciente ON Paciente.id = Anamnese.Paciente_id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id WHERE usuarios.sexo = 'f' ");
$homem = $stmt->selectManager("SELECT * FROM Anamnese INNER JOIN Paciente ON Paciente.id = Anamnese.Paciente_id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id WHERE usuarios.sexo = 'm' ");


$allPaciente[0] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 0+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[1] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 1+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[2] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 2+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[3] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 3+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[4] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 4+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[5] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 5+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[6] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 6+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[7] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 7+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[8] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 8+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[9] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 9+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[10] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 10+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");
$allPaciente[11] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE  Func_has_Paci.start > now() AND Anamnese.Funcionarios_id is null   and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 11+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018");

$pacientesAtendidos[0] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 0+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[1] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 1+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[2] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 2+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[3] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 3+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[4] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 4+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[5] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 5+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[6] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 6+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[7] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 7+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[8] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 8+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[9] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 9+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[10] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 10+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[11] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 11+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2018 AND Func_has_Paci.funcionarios_id ");


$pacientes = $stmt->selectManager("SELECT Func_has_Paci.*, Paciente.*, Func_has_Paci.* , usuarios.* FROM Func_has_Paci INNER JOIN Paciente INNER JOIN Funcionarios ON Func_has_Paci.Funcionarios_id = Funcionarios.id AND Func_has_Paci.Paciente_id = Paciente.id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id LEFT OUTER JOIN Medicamento ON Medicamento.Paciente_id = Paciente.id  WHERE Medicamento.Funcionarios_id is null  and Funcionarios.usuarios_id =" . \Ballybran\Helpers\Security\Session::get('ID'));
?>


<div class="container" id="features" >
    <div class="col-sm-12">
        <div class="row ">
            <div class="col-lg-12 cartao" >

                <div class="col-lg-3 4u 12u(mobile)">
                    <?php if (!empty($this->UserPhoto['path'])) { ?>
                        <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7 img-responsive img-circle" alt="<?php echo $this->UserPhoto['name']; ?>" />
                    <?php } else {
                        ?>
                        <img  src="<?php echo URL . DIR_FILE ?>Public/images/profile-icon.png" class="col-lg-7  img-responsive img-circle"  />
                    <?php } ?>
                </div>

                <div class="col-lg-4 4u 12u(mobile) text-left">
                    <h3>Contacto</h3>

                    <strong>Nome: </strong><?php echo $this->user['firstname'] . "\t" . $this->user['lastname']; ?><br>
                    <strong>Telefone: </strong><?php echo $this->user['telephone']; ?><br>
                    <strong>Email: </strong><?php echo $this->user['email']; ?><br>
                </div>
                <div class="col-lg-4 4u 12u(mobile) text-left">
                    <h3>Endereço</h3>
                    <strong>Endereço 1: </strong><?php echo $this->user['address_1'] ?><br>
                    <strong>Endereço 2: </strong><?php echo $this->user['address_2']; ?><br>
                    <strong>Cidade: </strong><?php echo $this->user['city']; ?><br>
                    <strong>País: </strong><?php echo $this->user['country']; ?><br>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12 col-sm-6">
        <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
            <div class="btn-group" role="group">
                <div  id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    <div class="hidden-xs">Painel</div>
                </div>
            </div>
            <div class="btn-group" role="group">
                <div  id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    <div class="hidden-xs">Pacientes</div>
                </div>
            </div>
            <div class="btn-group" role="group">
                <div  id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                    <div class="hidden-xs">Pacientes na lista</div>
                </div>
            </div>
            <div class="btn-group" role="group">
                <div  id="stars" class="btn btn-default" href="#tab4" data-toggle="tab"><span class="glyphicon glyphicon" aria-hidden="true"></span>
                    <div class="hidden-xs">Pagamentos </div>
                </div>
            </div>
            <div class="btn-group" role="group">
                <div  id="stars" class="btn btn-default" href="#tab5" data-toggle="tab"><span class="glyphicon glyphicon-setting" aria-hidden="true"></span>
                    <div class="hidden-xs">Configurações</div>
                </div>
            </div>
            <div class="btn-group" role="group">
                <div  id="favorites" class="btn btn-default" href="#tab6" data-toggle="tab"><span class="glyphicon glyphicon-chart" aria-hidden="true"></span>
                    <div class="hidden-xs">Agenda</div>
                </div>
            </div>
        </div>

        <div class="panel panel-info col-lg-12">
            <div class="tab-content">
                <div class="tab-pane fade in active" id="tab1">
                    <br><br>
                    <!--- blocos de contagem-->
                    <div class="row">
                        <div class="col-lg-2 col-sm-6">
                            <div class="circle-tile ">
                                <a href="#"><div class="circle-tile-heading dark-blue"><i class=""></i></div></a>
                                <div class="circle-tile-content dark-blue">
                                    <div class="circle-tile-description text-faded"> Novos</div>
                                    <div class="circle-tile-number text-faded "> <?php echo count($novos); ?></div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-2 col-sm-6">
                            <div class="circle-tile ">
                                <a href="#"><div class="circle-tile-heading dark-orange"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                <div class="circle-tile-content dark-orange">
                                    <div class="circle-tile-description text-faded"> Em Espera </div>
                                    <div class="circle-tile-number text-faded "> <?php echo count($emEspera); ?></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 col-sm-6">
                            <div class="circle-tile ">
                                <a href="#"><div class="circle-tile-heading dark-success"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                <div class="circle-tile-content dark-success">
                                    <div class="circle-tile-description text-faded"> Agendados</div>
                                    <div class="circle-tile-number text-faded "><?php echo count($agendados); ?></div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-2 col-sm-6">
                            <div class="circle-tile ">
                                <a href="#"><div class="circle-tile-heading red"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                <div class="circle-tile-content red">
                                    <div class="circle-tile-description text-faded"> Atendidos </div>
                                    <div class="circle-tile-number text-faded "><?php echo count($atendidos); ?></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 col-sm-6">
                            <div class="circle-tile ">
                                <a href="#"><div class="circle-tile-heading dark-blue-dark"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                <div class="circle-tile-content dark-blue-dark ">
                                    <div class="circle-tile-description text-faded"> Faltaram </div>
                                    <div class="circle-tile-number text-faded "><?php echo count($faltaram); ?></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row ">

                        <div class="col-lg-6 u 12u(mobile)">
                            <div class="card">

                                <div class="header">
                                    <h4 class="titles">Estatisticas de Paciente</h4>
                                </div>
                                <div class="content">

                                    <canvas id="barChart"  width="400" height="200"></canvas>

                                    <div class="footer">
                                        <div class="legend">
                                        </div>
                                        <hr>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end -->

                        <div class="col-lg-6">
                            <div class="card">

                                <div class="header">
                                    <h4 class="titles">Estatisticas de Paciente Por Sexo</h4>
                                </div>
                                <div class="content">

                                    <canvas id="barSexo"  width="400" height="200"></canvas>

                                    <div class="footer">
                                        <div class="legend">
                                        </div>
                                        <hr>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end -->

                        <div class="col-lg-12 4u 12u(mobile)">
                            <div class="card">

                                <div class="header">
                                    <h4 class="titles">Estatisticas Anual de Paciente</h4>
                                </div>
                                <div class="content">
                                    <canvas id="totalPaciente" class="ct-chart"></canvas>

                                    <div class="footer">
                                        <div class="legend">
                                        </div>
                                        <hr>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end -->


                        <!-- <div class="col-md-12">
                           <div class="card ">
                               <div class="header">
                                   <h4 class="titles">2014 Sales</h4>
                                   <p class="category">All products including Taxes</p>
                               </div>
                               <div class="content">
                                   <div id="secretaria"></div>

                                   <div class="footer">
                                       <div class="legend">
                                           <i class="fa fa-circle text-info"></i> Tesla Model S
                                           <i class="fa fa-circle text-danger"></i> BMW 5 Series
                                       </div>
                                       <hr>
                                       <div class="stats">
                                           <i class="fa fa-check"></i> Data information certified
                                       </div>
                                   </div>
                               </div>
                           </div>
                       </div>  end -->

                    </div>
                </div>

                <div class="tab-pane fade in" id="tab2">
                    <br>

                    <div class="row" style="min-height:300px;">
                        <div class="col-lg-12 4u 12u(mobile)">

                            <div class="col-xs-8">
                                <!-- required for floating -->
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs ">
                                    <li class="active"><a href="#ListPaci" data-toggle="tab">Pacientes por atender</a></li>
                                    <li><a href="#addPaci" data-toggle="tab" class="glyphicon glyphicon-user ">Novo Paciente</a></li>
                                    <li><a href="#retorno" data-toggle="tab" class="glyphicon glyphicon-user ">Consulta de Retorno </a></li>


                                </ul>
                            </div>
                            <div class="col-xs-12">
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div class="tab-pane active remove" id="ListPaci">
                                        <a href="<?php echo URL; ?>account/printConsulta" class="btn btn-success" target="_blank">Imprimir Lista</a>
                                        <a style="float:right;"  href="<?php echo URL ?>secretaria/customers"><i class="glyphicon glyphicon-list" > Lista Completa</i></a>



                                        <div id="consultListCadastro">
                                            <input type="text" class="search form-control" placeholder="Buscar Paciente"  />
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th class="sort" data-sort="name3">Name </th>
                                                        <th class="sort" data-sort="sexo3">Sexo</th>
                                                        <th class="sort" data-sort="date3">data do cadastro</th>
                                                        <th class="sort" data-sort="consult3">Telefone</th>
                                                        <th class="sort" data-sort="consult3">Especialidade</th>
                                                        <th class="sort" data-sort="consult3">Info</th>
                                                        <th class="sort" data-sort="consult3">Marcar</th>
                                                    </tr>
                                                </thead>
                                                <tbody class="list">

                                                    <?php foreach ($this->consultas as $item => $value) { ?>

                                                        <tr>
                                                            <td class="id2" style="display:none;"><?php echo $item['id'] + 1; ?></td>
                                                            <td class="name3"><?php echo $value['firstname'] . "\t" . $value['lastname']; ?></td>
                                                            <td class="sexo3"><?php echo $value['sexo'] == 'f' ? "Feminino " : "Maculino"; ?></td>
                                                            <td class="date3"><?php echo $value['createTime']; ?></td>
                                                            <td><?php echo $value['telephone']; ?></td>
                                                            <?php
                                                            echo Form::open(['method' => 'post', 'action' => URL . 'secretaria/inserPasciente', 'id' => 'cadastroPaciente']);
                                                            echo Form::input(['type' => 'hidden', 'name' => 'usuarios_id', 'value' => $value['id']]);
                                                            echo Form::input(['type' => 'hidden', 'name' => 'create_dt', 'value' => \Ballybran\Helpers\Time\Timestamp::dataTime()]);
                                                            ?>
                                                            <td>
                                                                <select class="form-control" name="Especialidade_id" style='color:#000000;'>
                                                                    <option>--</option>
                                                                    <?php foreach ($this->especialidades as $keys => $val) : ?>
                                                                        <option value="<?php echo $val['id']; ?>"><?php echo $val['espNome']; ?> </option>
                                                                        <?php endForeach; ?>
                                                                </select>
                                                            </td>
                                                            <td> <?php echo Form::textBox(['name' => 'info', 'placeholder' => 'info']); ?> </td>
                                                            <td><?php echo Form::button(['type' => "submit", 'value' => 'Inserir']); ?></td>
                                                            <?php
                                                            echo Form::close();
                                                            ?>
                                                        </tr>




                                                    <?php } ?>


                                                </tbody>
                                            </table>






                                            <?php if ($this->consultas == "" || empty($this->consultas)) echo "<h3>Está vazio :) </h3><br><br>"; ?>
                                            <ul class="pagination"></ul>

                                        </div>

                                        <div class="clearfix"></div>

                                    </div>



                                    <div class="tab-pane" id="addPaci">

                                        <br>

                                        <?php
                                        echo Form::open(["class" => "form-inline", "role" => "form", 'method' => 'post', 'action' => URL . 'User/secretariaCreateNewPaciente', 'files' => 'enctype=multipart/form-data', 'name' => 'signUp', 'class' => 'form-signin', 'style' => 'width:60%;']);
                                        ?>


                                        <label class="control-label" for="input-firstname">Primeiro Nome</label>
                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'firstname', 'id' => 'user-name', 'class' => 'form-control', 'autocomplete' => "off"]);
                                        ?>
                                        <label class="control-label" for="input-firstname">Ultimo Nome</label>
                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'lastname', 'id' => 'user-name', 'class' => 'form-control', 'autocomplete' => "off"]);
                                        ?>
                                        <label class="control-label" for="input-firstname">Nome para Usuario</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'username', 'id' => 'user-name', 'class' => 'form-control', 'autocomplete' => "off"]);
                                        ?>

                                        <label class="control-label" for="input-firstname">Email</label>

                                        <?php
                                        echo Form::input(['type' => 'email', 'name' => 'email', 'id' => 'user-name', 'class' => 'form-control', 'autocomplete' => "off"]);
                                        ?>

                                        <label class="control-label" for="input-firstname">Telefone</label>

                                        <?php
                                        echo Form::input(['type' => 'number', 'name' => 'telephone', 'id' => 'user-name', 'class' => 'form-control', 'autocomplete' => "off"]);
                                        ?>

                                        <select name="sexo" id="" class="form-control" style="width: 200px;">
                                            <option value="f">Feminino</option>
                                            <option value="m">Masculino</option>
                                        </select>

                                        <label class="control-label" for="input-firstname">Password</label>

                                        <?php
                                        echo Form::input(['type' => 'password', 'name' => 'password', 'id' => 'user-name', 'class' => 'form-control', 'autocomplete' => "off"]);
                                        ?>

                                        <hr>
                                        <?php
                                        echo Form::button(['type' => 'submit', 'class' => 'btn btn-primary', 'id' => 'send_request', 'value' => 'Cadastrar']);
                                        ?>

                                        <?php
                                        echo Form::close();
                                        ?>


                                    </div>

                                    <div class="tab-pane" id="retorno">


                                        <div id="consultListCadastroRetorno">
                                            <input type="text" class="search form-control" placeholder="Buscar Paciente"  />
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th class="sort" data-sort="nameRetorno">Name </th>
                                                        <th class="sort" data-sort="sexoRetorno">Sexo</th>
                                                        <th class="sort" data-sort="dateRetorno">data do cadastro</th>
                                                        <th class="sort" data-sort="telefoneRetorno">Telefone</th>
                                                        <th class="sort" data-sort="infocompleta">Info Completa</th>
                                                        <th class="sort">Acção</th>
                                                    </tr>
                                                </thead>
                                                <tbody class="list">

                                                    <?php foreach ($this->retornoDoPaciente as $item => $value) { ?>

                                                        <tr>
                                                            <!-- <td class="idretorno" style="display:none;"><?php echo $item['id'] + 1; ?></td> -->
                                                            <td class="nameRetorno"><?php echo $value['firstname'] . " " . $value['lastname']; ?></td>
                                                            <td class="sexoRetorno"><?php echo $value['sexo'] == 'f' ? "Feminino " : "Maculino"; ?></td>
                                                            <td class="dateRetorno"><?php echo $value['createTime']; ?></td>
                                                            <td class="telefoneRetorno"><?php echo $value['telephone']; ?></td>
                                                            <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#retorno-<?php echo $value['id']; ?>" data-whatever="@getbootstrap">Ver Perfil</button>
                                                            </td>
                                                            <td ><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#retorno-<?php echo $value['id']; ?>" data-whatever="@getbootstrap">Marcar Nova Consulta</button>
                                                            </td>

                                                        </tr>
                                                    <div class="modal fade" id="retorno-<?php echo $value['id']; ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title" id="exampleModalLabel"><?php echo $value['firstname']; ?></h5>
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <?php
                                                                    echo Form::open(['action' => URL . 'account/insertconsulta', 'method' => 'post']);
                                                                    echo Form::input(['type' => 'hidden', 'name' => 'usuarios_id', 'value' => $value['id']]);
//                            echo Form::input(['type'=>'hidden', 'name'=>'Situacao_id' ]);
                                                                    echo Form::input(['type' => 'hidden', 'name' => 'create_dt', 'value' => \Ballybran\Helpers\Time\Timestamp::dataTime()]);
                                                                    ?>
                                                                    <div class="form-group">
                                                                        <label for="recipient-name" class="form-control-label">Convenio:</label>
                                                                        <select name="Convenio_id" id="" class="form-control">
                                                                            <option>Seleciona uma Opçao</option>
                                                                            <?php foreach ($this->convenio as $key => $convenio) : ?>
                                                                                <option value="<?php echo $convenio['id']; ?>"><?php echo $convenio['convNome']; ?></option>
                                                                            <?php endforeach; ?>
                                                                        </select>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label for="recipient-name" class="form-control-label">Especialidade (opcional):</label>
                                                                        <select name="Especialidade_id" id="" class="form-control">
                                                                            <option value="">Seleciona uma Opçao</option>
                                                                            <?php foreach ($this->especialidades as $key => $especialidades) : ?>
                                                                                <option value="<?php echo $especialidades['id']; ?>"><?php echo $especialidades['espNome']; ?></option>
                                                                            <?php endforeach; ?>
                                                                        </select>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label for="recipient-name" class="form-control-label">Antecedente de doença cróonica como HTA, DM ou outras:</label>
                                                                        <?php
                                                                        echo Form::input(['type' => 'text', 'name' => 'ante', 'placeholder' => '', 'class' => 'form-control']);
                                                                        ?>
                                                                    </div>
                                                                    <div class="form-group">
                                                                        <label for="recipient-name" class="form-control-label">Informa aqui:</label>

                                                                        <?php
                                                                        echo Form::textBox(['type' => 'text', 'name' => 'info', 'placeholder' => '', 'class' => 'form-control']);
                                                                        ?>


                                                                    </div>
                                                                    <div class="modal-footer">
                                                                    </div>
                                                                    <?php
                                                                    echo Form::button(['type' => 'submit', 'class' => 'btn btn-primary', 'value' => 'Fazer consulta']);
                                                                    ?>
                                                                    <?php
                                                                    echo Form::close();
                                                                    ?>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>


                                                <?php } ?>


                                                </tbody>
                                            </table>
                                            <ul class="pagination"></ul>






                                            <?php if ($this->consultas == "" || empty($this->consultas)) echo "<h3>Está vazio :) </h3><br><br>"; ?>
                                            <ul class="pagination"></ul>

                                        </div>

                                    </div><!-- end retorno -->



                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>

                </div>



                <div class="tab-pane fade in" id="tab3">
                    <br>

                    <div class="row" style="min-height:300px;">
                        <div  class="col-sm-12">
                            <div class="col-xs-6">
                                <!-- required for floating -->
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs ">
                                    <li class="active"><a href="#func" data-toggle="tab">Lista  de Paciente</a></li>
                                    <li><a href="#profile" data-toggle="tab"></a></li>
                                    <li><a href="#messages" data-toggle="tab"></a></li>
                                    <li><a href="#settings" data-toggle="tab"></a></li>
                                </ul>
                            </div>
                            <div class="col-xs-12">
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div class="tab-pane active" id="func">

                                        <a href="<?php echo URL; ?>account/printAllPacient" class="btn btn-success" target="_blank">Imprimir Lista</a>

                                        <div id="consultListAgend">
                                            <input type="text" class="search form-control" placeholder="Buscar Paciente"  />
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th class="sort" data-sort="name1">Name </th>
                                                        <th class="sort" data-sort="date1">Aria da consulta</th>
                                                        <th class="sort" data-sort="valor1">Preço </th>
                                                        <th class="sort" data-sort="titulo1">Situação</th>
                                                        <th>Cancelar</th>
                                                    </tr>
                                                </thead>
                                                <tbody class="list">

                                                    <?php foreach ($this->pacieteMedico as $key => $pacieteMedico) : ?>

                                                        <tr>
                                                            <td class="id1" style="display:none;"><?php echo $key['id'] + 1; ?></td>
                                                            <td class="name1"><?php echo $pacieteMedico['firstname'] . "\t" . $pacieteMedico['lastname']; ?></td>
                                                            <td class="date1"><?php echo $pacieteMedico['espNome']; ?></td>
                                                            <td class="valor1"><?php echo $pacieteMedico['espValor'] . "\t Kz"; ?></td>
                                                            <td class="titulo1">

                                                                <?php
                                                                $triagem = $stmt->selectManager(" SELECT * FROM Exame_Fisico INNER JOIN Paciente ON Exame_Fisico.Paciente_id = Paciente.id WHERE Paciente.id = " . $pacieteMedico['id']);

                                                                if ($pacieteMedico['situ_nome'] == "Aberto") {
                                                                    ?>
                                                                    <small class="btn btn-danger"  data-toggle="modal" data-target="#exampleModalLongPagar-<?php echo $pacieteMedico["lastname"]; ?>"><?php echo $pacieteMedico['situ_nome']; ?></small>
                                                                <?php } else { ?>
                                                                    <small class='btn btn-success'>Paga</small>
                                                                <?php } ?>
                                                            </td>
                                                            <td><a href="<?php echo URL; ?>secretaria/deletaragendamento/<?php echo $pacieteMedico['id']; ?>">Cancelar</a></td>
                                                        </tr>


                                                        <!-- Modal 1 -->
                                                    <div class="modal fade col-lg-12" id="exampleModalLongPagar-<?php echo $pacieteMedico['lastname']; ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                                                        <div class="modal-dialog modal-lg" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header cartao">
                                                                    <h2 class="modal-title" id="exampleModalLongTitle">Distribuição de Pacientes</h5>
                                                                        <h5 class="modal-title" id="exampleModalLongTitle">Nome: <?php echo $pacieteMedico['firstname'] . "\t" . $pacieteMedico['lastname']; ?>"</h5>


                                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                            <span aria-hidden="true">x</span>
                                                                        </button>
                                                                </div>
                                                                <div class="modal-body">

                                                                    <div class="card">
                                                                        <strong>Queixas do doente:</strong>
                                                                        <p>
                                                                            <?php echo $pacieteMedico['info']; ?></p>
                                                                    </div>

                                                                    <div class="container col-sm-12">

                                                                        <div class="col-lg-5">
                                                                            <?php echo Form::open(['method' => 'post', 'action' => URL . 'finance/insertCredito']); ?>

                                                                            <div class="form-group">
                                                                                <!--                                                                                <label class="control-label" for="input-firstname">Data da Consulta: </label>-->
                                                                                <?php
                                                                                echo Form::input(['type' => 'hidden', 'name' => 'dtPag', 'value' => \Ballybran\Helpers\Time\Timestamp::dataTime()]);
                                                                                echo Form::input(['type' => 'hidden', 'name' => 'Paciente_id', 'value' => $pacieteMedico['id'], 'class' => 'form-control']);
                                                                                echo Form::input(['type' => 'hidden', 'name' => 'Especialidade_id', 'value' => $pacieteMedico['Especialidade_id'], 'class' => 'form-control']);
                                                                                ?>
                                                                            </div>
                                                                            <div class="form-group">
                                                                                <label class="control-label" for="input-firstname">Preço da Consulta em Kz</label>

                                                                                <?php
                                                                                echo Form::input(['type' => 'text', 'name' => 'CreditoValor', 'placeholder' => $pacieteMedico['espValor'], 'class' => 'col-lg-2 form-control']);
                                                                                ?>
                                                                            </div>
                                                                            <div class="form-group">
                                                                                <label class="control-label" for="input-firstname">Conta Movimento</label>
                                                                                <select class="form-control" name="ContaMovimento_id" id="exampleFormControlSelect2">
                                                                                    <option>--</option>
                                                                                    <?php foreach ($this->moviento as $movimento) { ?>
                                                                                        <option  value="<?php echo $movimento['id'] ?>"><?php echo $movimento['Cnome'] ?></option>
                                                                                    <?php } ?>
                                                                                </select>
                                                                            </div>
                                                                            <div class="form-group">
                                                                                <label class="control-label" for="input-firstname">Forma de Pagamento</label>
                                                                                <select class="form-control" name="FormaPagamento_id" id="exampleFormControlSelect1">
                                                                                    <option>--</option>
                                                                                    <?php foreach ($this->formaPagamento as $pagamento) { ?>

                                                                                        <option value="<?php echo $pagamento['id'] ?>"><?php echo $pagamento['FPnome'] ?></option>
                                                                                    <?php } ?>
                                                                                </select>
                                                                            </div>

                                                                        </div>
                                                                        <br>

                                                                        <div class="col-lg-5">

                                                                            <div class="form-group">
                                                                                <label class="control-label" for="input-firstname">Escolher medico da Especialidade: </label>

                                                                                <select class="form-control"  name="Funcionarios_id"  id="exampleFormControlSelect2">
                                                                                    <?php
                                                                                    $medicos = $stmt->selectManager("SELECT    usuarios.firstname, Funcionarios.id FROM Funcionarios INNER JOIN Especialidade ON Especialidade.id = Funcionarios.Especialidade_id INNER JOIN usuarios ON usuarios.id = Funcionarios.usuarios_id     INNER JOIN Paciente ON Paciente.Especialidade_id = Especialidade.id WHERE Paciente.id = " . $pacieteMedico['id']);
                                                                                    ?>

                                                                                    <option>--</option>

                                                                                    <?php
                                                                                    foreach ($medicos as $keys => $val) :


                                                                                        $count = $stmt->selectManager("SELECT COUNT(*) FROM Paciente LEFT OUTER JOIN Anamnese on Paciente.id = Anamnese.Paciente_id  INNER JOIN Func_has_Paci on  Paciente.id = Func_has_Paci.Paciente_id INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id WHERE  Anamnese.Paciente_id is null AND Funcionarios.id = " . $val['id'])[0];
                                                                                        foreach ($count as $key => $counts) {
                                                                                            ?>

                                                                                            <option value="<?php echo $val['id']; ?>"><?php echo $val['firstname'] . "\t|\t n de pacientes ({$counts})"; ?> </option>

                                                                                        <?php } endForeach; ?>
                                                                                </select>
                                                                            </div>

                                                                            <div class="form-group">
                                                                                <label class="control-label" for="input-firstname">Situação: </label>

                                                                                <select class="form-control"  name="Situacao_id"  id="exampleFormControlSelect2">

                                                                                    <option value="2">Fechado</option>
                                                                                    <option value="1">Aberto</option>

                                                                                </select>
                                                                            </div>

                                                                            <div class="form-group">
                                                                                <label class="control-label" for="input-firstname">Horario para Consulta:</label>
                                                                                <?php echo Form::input(['type' => 'text ', 'id' => 'datetimepicker' . $pacieteMedico['id'], 'name' => 'start', 'class' => 'form-control', 'autocomplete' => "off"]); ?>
                                                                            </div>
                                                                            <div class="form-group">
                                                                                <?php
                                                                                echo Form::input(['type' => 'hidden', 'name' => 'Func_dt', 'class' => 'form-control', 'value' => \Ballybran\Helpers\Time\Timestamp::dataTime()]);
                                                                                ?>
                                                                            </div>

                                                                            <script>

                                                                                jQuery.datetimepicker.setLocale('pt');

                                                                                jQuery('#datetimepicker<?php echo $pacieteMedico['id']; ?>').datetimepicker({
                                                                                });
                                                                            </script>





                                                                        </div><!-- end consulta -->

                                                                    </div>
                                                                    <div class="modal-footer">
                                                                        <?php echo Form::button(['type' => 'submit', 'class' => 'btn btn-primary', 'value' => 'Atualizar']); ?>
                                                                        <?php
                                                                        echo Form::close();
                                                                        ?>
                                                                        <?php if ($this->pacieteMedico == "" || empty($this->pacieteMedico)) echo "<h3>Está vazio :) </h3><br><br>"; ?>

                                                                    </div>

                                                                </div>

                                                            </div>
                                                        </div>
                                                    </div> <!-- modal 1 end -->





                                                <?php endforeach; ?>

                                                </tbody>


                                            </table>
                                            <ul class="pagination"></ul>


                                        </div>



                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="clearfix"></div>

                <div class="tab-pane fade in" id="tab4">
                    <br>

                    <div class="row" style="min-height:300px;">
                        <div  class="col-sm-12">
                            <div class="col-xs-6">
                                <!-- required for floating -->
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs ">
                                    <li class="active"><a href="#pacientepag" data-toggle="tab">Lista  de Consultas pagas</a></li>
                                    <li class="nop"><a href="#pacientFalta" data-toggle="tab">Lista  de Faltas</a></li>
                                </ul>
                            </div>
                            <div class="col-xs-12">
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div class="tab-pane active" id="pacientepag">
                                        <a href="<?php echo URL; ?>account/printAllPacientPayment" class="btn btn-success" target="_blank">Imprimir Lista</a>



                                        <div id="consultListPag">
                                            <input type="text" class="search form-control" placeholder="Buscar Paciente"  />
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th class="sort" data-sort="name2">Name </th>
                                                        <th class="sort" data-sort="date2">data de pagamento</th>
                                                        <th class="sort" data-sort="consulta2">Data da Consulta</th>
                                                        <th class="sort" data-sort="valor2">Valor a Pagar</th>
                                                        <th class="sort" data-sort="valorP2">Valor Pago</th>
                                                        <th class="sort" data-sort="qualt2">Qt. a Faltar</th>
                                                    </tr>
                                                </thead>
                                                <tbody class="list">

                                                    <?php foreach ($this->passienteSecretaria as $item => $passienteSecretaria) { ?>

                                                        <tr>
                                                            <td class="id2" style="display:none;"><?php echo $item['id'] + 1; ?></td>
                                                            <td class="name2"><?php echo $passienteSecretaria['firstname'] . "\t" . $passienteSecretaria['lastname']; ?></td>
                                                            <td class="date2"><?php echo $passienteSecretaria['dtPag']; ?></td>
                                                            <td class="consulta2"><?php echo $passienteSecretaria['start']; ?></td>
                                                            <td class="valor2"><?php echo $passienteSecretaria['espValor']; ?> Kz</td>
                                                            <td class="valorP2"><?php echo $passienteSecretaria['CreditoValor']; ?> Kz</td>
                                                            <?php
                                                            $total = $passienteSecretaria['espValor'] - $passienteSecretaria['CreditoValor'];
                                                            if ($total > 0) {
                                                                ?>
                                                                <td class="qualt2 btn-danger"><?php echo $total; ?> Kz</td>
                                                            <?php } else { ?>
                                                                <td class="qualt2 btn-success"><?php echo $total; ?> Kz</td>
                                                            <?php } ?>

                                                        </tr>
                                                    <?php }
                                                    ?>


                                                </tbody>
                                            </table>
                                            <ul class="pagination"></ul>

                                        </div>

                                    </div>
                                    <div class="tab-pane " id="pacientFalta">
                                        <a href="<?php echo URL; ?>account/printAllPacientPayment" class="btn btn-success" target="_blank">Imprimir Lista</a>



                                        <div id="consultListFalta">
                                            <input type="text" class="search form-control" placeholder="Buscar Paciente"  />
                                            <table class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th class="sort" data-sort="name4">Name </th>
                                                        <th class="sort" data-sort="consulta4">Data da Consulta</th>
                                                        <th class="sort" data-sort="titulo4">Medico</th>
                                                    </tr>
                                                </thead>
                                                <tbody class="list">

                                                    <?php foreach ($faltaram as $item => $passienteSecretaria) { ?>
                                                        <tr>
                                                            <td class="id4" style="display:none;"><?php echo $item['id'] + 1; ?></td>
                                                            <td class="name4"><?php echo $passienteSecretaria['firstname'] . "\t" . $passienteSecretaria['lastname']; ?></td>
                                                            <td class="consulta4"><?php echo $passienteSecretaria['start']; ?></td>
                                                            <td class="titulo4"><?php echo $passienteSecretaria['titulo']; ?></td>
                                                        </tr>
                                                    <?php } ?>

                                                </tbody>
                                            </table>
                                            <ul class="pagination"></ul>

                                        </div>                                        </div>
                                </div>

                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade in" id="tab5">
                    <br><br>

                    <div class="row" style="min-height:300px;">
                        <div  class="col-lg-12">
                            <div class="col-xs-8">
                                <!-- required for floating -->
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs">
                                    <li class="active"><a href="#home" data-toggle="tab">Dados Pessoais</a></li>
                                    <li><a href="#info" data-toggle="tab">Atualizar dados</a></li>
                                    <li><a href="#password" data-toggle="tab">Password</a></li>
                                    <li><a href="#especialidade" data-toggle="tab">Especialidades</a></li>
                                    <li><a href="#convenio" data-toggle="tab">Cad. Convénio</a></li>
                                </ul>
                            </div>
                            <div class="col-xs-9">
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div class="tab-pane active" id="home">
                                        <br><br><br>

                                        <div class="row">

                                            <div class="panel panel-info col-lg-12" >
                                                <div class="panel-heading">
                                                    <h3 class="panel-title">Meus Dados</h3>
                                                </div>
                                                <div class="panel-body">
                                                    <div class="row">

                                                        <div class=" col-md-9 col-lg-9 ">
                                                            <div class="col-lg-7 4u 12u(mobile)">

                                                                <?php if (!empty($this->UserPhoto['path'])) { ?>

                                                                    <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7 image img-responsive img-thumbnail" alt="<?php echo $this->UserPhoto['name']; ?>" />
                                                                    <?php
                                                                    if (Session::exist()) {
                                                                        ?>
                                                                        <a href="<?php echo URL; ?>account/deleteImage"  class="glyphicon glyphicon-remove" >delete</a>
                                                                        <?php
                                                                    }
                                                                } else {
                                                                    echo "nao tem imagem";
                                                                }
                                                                ?>
                                                            </div>
                                                            <br>
                                                            <table class="table table-user-information">
                                                                <tbody class="list">
                                                                    <tr>
                                                                        <td>Especialidade:</td>
                                                                        <td><?php echo $this->user['telephone']; ?></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Contratado em::</td>
                                                                        <td><?php echo $this->user['createTime']; ?></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Data de Nascimento</td>
                                                                        <td><?php echo $this->user['dataNascimento']; ?></td>
                                                                    </tr>

                                                                    <tr>
                                                                    <tr>
                                                                        <td>Genero</td>

                                                                        <td>
                                                                            <?php echo $this->user['sexo'] != "" ? $this->user['sexo'] == 'f' ? "Feminino" : "Masculino" : NULL; ?>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Endereço</td>
                                                                        <td><?php echo $this->user['address_1']; ?></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Email</td>
                                                                        <td><a href="mailto:<?php echo $this->user['email']; ?>"><?php echo $this->user['email']; ?></a></td>
                                                                    </tr>
                                                                <td>Numero do Telefone</td>
                                                                <td><?php echo $this->user['telephone']; ?><br><br><?php echo $this->user['telephone2']; ?>(Mobile)
                                                                </td>

                                                                </tr>

                                                                </tbody>
                                                            </table>
                                                            <ul class="pagination"></ul>

                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <!-- profile end -->

                                    </div>
                                    <div class="tab-pane" id="info">
                                        <br><br>
                                        <form method="post" action="<?php echo URL; ?>account/insertImageUser" enctype="multipart/form-data">
                                            <label for="pic">Faça o Uploads de uma foto para o perfil:</label>
                                            <input type="file" name="archive[]" id="pic" />
                                            <label for="colorWell">Qualidade:</label>
                                            <input type="number" value="50" name="quality"/>
                                            <label for="colorWell">Rotação:</label>
                                            <input type="number"  value="00" name="degree" />
                                            <label for="colorWell">Color:</label>
                                            <input type="color" name="color" value="#ff0000" class="contact-form" id="colorWell" />
                                            <input type="submit" value="Carregar" />
                                        </form>

                                        <h4>My Account</h4>


                                        <?php
                                        echo Form::open(['method' => 'post', 'action' => URL . 'account/updates', 'name' => '', 'class' => 'form-signin', 'style' => 'width:50%']);
                                        ?>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">First Name</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'firstname', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['firstname']]);
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Last Name</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'lastname', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['lastname']]);
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">User Name</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'username', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['username']]);
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">E-mail</label>

                                            <?php
                                            echo Form::input(['type' => 'email', 'name' => 'email', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['email']]);
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Data de Nascimento</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'dataNascimento', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['dataNascimento']]);
                                            ?>

                                        </div>
                                        <small>Your Address</small>
                                        <hr>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Telephone</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'telephone', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['telephone']]);
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Company</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'company', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['company']]);
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Address 1</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'address_1', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['address_1']]);
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Address 2</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'address_2', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['address_2']]);
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Bairro</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'bairro', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['bairro']]);
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Post Code</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'postcode', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['postcode']]);
                                            ?>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">City</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'city', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['city']]);
                                            ?>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Country</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'country', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['country']]);
                                            ?>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Region/State</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'zone', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['zone']]);
                                            ?>

                                        </div>
                                        <?php
                                        echo Form::input(['type' => 'hidden', 'name' => 'id', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['id']]);
                                        ?>



                                        <div class="form-group">
                                            <br/>
                                            <button class="btn btn-primary btn-inverse btn-default" onclick="updateUser(<?php echo $this->user['id']; ?>)" ><p class="glyphicon glyphicon-refresh "></p></button>
                                            <a class="btn btn-danger deletar" href="<?php echo URL ?>account/deletes/<?php echo $this->user['id']; ?>"><p class="glyphicon glyphicon-trash "></p></a>

                                        </div>

                                        <?php
                                        echo Form::close();
                                        ?>
                                    </div>
                                    <div class="tab-pane" id="password">
                                        <br><br>
                                        <section>

                                            <div class="row">
                                                <form  class="form-horizontal" action="<?php echo URL; ?>account/managePassword" name="perfil" method="post">

                                                    <div class="form-group">
                                                        <label for="exampleInputPassword1">Password</label>
                                                        <input type="password" class="form-control" placeholder="Senha antiga" name="oldPassword" id="exampleInputPassword1">
                                                        <br>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="exampleInputPassword1">Password</label>
                                                        <input type="password" class="form-control" placeholder="Senha Nova" name="password" id="exampleInputPassword1">
                                                        <input type="hidden" class="form-control" name="id" value="<?php echo $this->user['id']; ?>"  id="exampleInputPassword1">
                                                        <br>
                                                    </div>
                                                    <div class="col-sm-8">
                                                        <button type="submit" class="btn btn-info">Atualizar</button>
                                                    </div>

                                                </form>
                                            </div>
                                        </section>
                                    </div>

                                    <div class="tab-pane" id="especialidade">
                                        <br><br>


                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#especialidadeModal" data-whatever="@getbootstrap">Criar</button>
                                        <br><br>


                                        <div class="modal fade" id="especialidadeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Espcialidade</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">

                                                        <?php echo Form::open(['action' => URL . 'secretaria/insertEspecialidade', 'method' => 'post']); ?>
                                                        <div class="form-group">
                                                            <label for="recipient-name" class="form-control-label">Nome da Especialidade:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'text', 'class' => 'form-control', 'name' => 'espNome', 'placeholder' => 'Insere uma especialidade']);
                                                            ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="recipient-name" class="form-control-label">Valor em Kz:</label>
                                                            <?php echo Form::input(['type' => 'text', 'name' => 'espValor', 'class' => 'form-control', 'placeholder' => 'Insere valor']); ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="recipient-name" class="form-control-label">Tipo de Receia:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'text', 'name' => 'TipoReceita_id', 'class' => 'form-control', 'placeholder' => 'Insere uma Tipo de Receita']);
                                                            ?>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <?php
                                                        echo Form::submit(['type' => 'submit', 'value' => 'Criar']);
                                                        echo Form::close();
                                                        ?>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Nome da Especialidade</th>
                                                    <th>Nome da Valor da Especialidade</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list">
                                                <?php foreach ($this->especialidades as $especialidade) { ?>
                                                    <tr>
                                                        <td><?php echo $especialidade['espNome']; ?></td>
                                                        <td><?php echo $especialidade['espValor']; ?></td>
                                                        <td><a href="<?php echo URL; ?>secretaria/deleteEspecialidade/<?php echo $especialidade['id']; ?>">deletar</a></td>
                                                    </tr>
                                                <?php } ?>

                                            </tbody>
                                        </table>
                                        <ul class="pagination"></ul>



                                    </div>
                                    <div id="convenio" class="tab-pane">
                                        <br><br>
                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#convenioModal" data-whatever="@getbootstrap">Criar Convenios</button>
                                        <br><br>


                                        <table class="table table-bordered table-inverse">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>F ome do Convenio</th>
                                                    <th>Telefone</th>
                                                    <th>Responsavel</th>
                                                    <th>Email</th>
                                                    <th>deletar</th>
                                                </tr>
                                            </thead>
                                            <tbody class="list">
                                                <?php foreach ($this->convenio as $key => $value) : ?>
                                                    <tr>

                                                        <th scope="row"><?php echo ($key + 1); ?></th>
                                                        <td><?php echo $value['convNome'] ?></td>
                                                        <td><?php echo $value['telephone'] ?></td>
                                                        <td><?php echo $value['responsavel'] ?></td>
                                                        <td><?php echo $value['email'] ?></td>
                                                        <td><a href="<?php echo URL; ?>secretaria/deleteConvenio/<?php echo $value['id']; ?>">deletar</a></td>
                                                    </tr>
                                                <?php endforeach; ?>


                                            </tbody>
                                        </table>
                                        <ul class="pagination"></ul>

                                        <div class="modal fade" id="convenioModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Inserir dados</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">

                                                        <br><br>
                                                        <?php
                                                        echo Form::open(['method' => 'post', 'action' => URL . 'secretaria/createConvenio', 'files' => 'multipart/form-data']);
                                                        ?>

                                                        <div class="form-group">
                                                            <label for="pic">Faça o Uploads de uma foto para o perfil:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'file', 'name' => 'archive[]', "id" => 'pic', 'class' => 'form-control']);
                                                            ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="colorWell">Qualidade:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'number', 'name' => 'quality', 'class' => 'form-control']);
                                                            ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="colorWell">Rotação:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'number', 'name' => 'degree', 'value' => '00', 'class' => 'form-control']);
                                                            ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="colorWell">Color:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'color', 'name' => 'color', 'value' => '#ff0000', 'id' => 'colorWell', 'class' => 'form-control']);
                                                            ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="colorWell">Descrição:</label>
                                                            <?php
                                                            echo Form::textBox(['type' => 'text', 'name' => 'description', 'class' => 'form-control']);
                                                            ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="recipient-name" class="form-control-label">Nome do Convenio:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'text', 'name' => 'convNome', 'class' => 'form-control']);
                                                            ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="recipient-name" class="form-control-label">Telefone:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'text', 'name' => 'telephone', 'class' => 'form-control']);
                                                            ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="recipient-name" class="form-control-label">Responsavel:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'text', 'name' => 'responsavel', 'class' => 'form-control']);
                                                            ?>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="recipient-name" class="form-control-label">Email:</label>
                                                            <?php
                                                            echo Form::input(['type' => 'text', 'name' => 'email', 'class' => 'form-control']);
                                                            ?>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                                                            <?php
                                                            echo Form::submit(['type' => 'submit', 'value' => 'Cadastrar']);
                                                            ?>
                                                        </div>


                                                    </div>
                                                    <?php
                                                    echo Form::close();
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div><!--- end -->
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade in" id="tab6">

                    <br><br>
                    <div class="col-md-12">
                        <div class="header">
                            <div id="calendar"></div>
                            <div id="calendar1"></div>


                            <!-- Modal -->
                            <div id="createEventModal" class="modal fade" role="dialog">
                                <div class="modal-dialog">

                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Add Event</h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="control-group">
                                                <label class="control-label" for="inputPatient">Event:</label>
                                                <div class="field desc">
                                                    <input class="form-control" id="title" name="title" placeholder="Event" type="text" value="">
                                                </div>
                                            </div>

                                            <input type="hidden" id="startTime"/>
                                            <input type="hidden" id="endTime"/>



                                            <div class="control-group">
                                                <label class="control-label" for="when">When:</label>
                                                <div class="controls controls-row" id="when" style="margin-top:5px;">
                                                </div>
                                            </div>

                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                                            <button type="submit" class="btn btn-primary" id="submitButton">Save</button>
                                        </div>
                                    </div>

                                </div>
                            </div>


                            <div id="calendarModal" class="modal fade">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Event Details</h4>
                                        </div>
                                        <div id="modalBody" class="modal-body">
                                            <h4 id="modalTitle" class="modal-title"></h4>
                                            <div id="modalWhen" style="margin-top:5px;"></div>
                                        </div>
                                        <input type="hidden" id="eventID" />
                                        <div class="modal-footer">
                                            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                                            <button type="submit" class="btn btn-danger" id="deleteButton">Delete</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--Modal-->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<?php $url = URL . "cpanel/event"; ?>

<script>

    var PieChart = {
        type: "pie",
        data: {
            datasets: [{
                    data: [
                        [<?php echo json_encode(count($novos)); ?>],
                        [<?php echo json_encode(count($emEspera)); ?>],
                        [<?php echo json_encode(count($agendados)); ?>],
                        [<?php echo json_encode(count($atendidos)); ?>],
                        [<?php echo json_encode(count($faltaram)); ?>]
                    ],
                    backgroundColor: [
                        '#34495E',
                        '#F39C12',
                        '#419641',
                        '#E74C3C',
                        '#1D38D3'
                    ]
                }],
            labels: [
                ' Novos',
                ' Em espera',
                'Agendados',
                'Atendidos',
                'Faltaram'
            ]

        },
        options: {
            responsive: true
        }
    };
    var pie = document.getElementById('barChart').getContext('2d');
    window.line = new Chart(pie, PieChart);


    var PieChartSexo = {
        type: "pie",
        data: {
            datasets: [{
                    data:
                            [
                                [<?php echo json_encode(count($mulher)); ?>],
                                [<?php echo json_encode(count($homem)); ?>]


                            ],
                    backgroundColor: [
                        "#f7409e",
                        "#1DC7EA"
                    ]
                }],
            labels:
                    [
                        ' Mulher',
                        'Homem'
                    ]

        },
        options: {
            responsive: true
        }
    };
    var pies = document.getElementById('barSexo').getContext('2d');
    window.line = new Chart(pies, PieChartSexo);


    var myChart = {
        type: 'bar',
        data: {
            labels: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "julho", "Agosto", "Setembro", "Outrubto", "Noembro", "Dezembro"],
            datasets: [
                {
                    label: 'Pacientes em Espera',
                    data: [
                        [<?php echo json_encode(count($allPaciente[0])); ?>],
                        [<?php echo json_encode(count($allPaciente[1])); ?>],
                        [<?php echo json_encode(count($allPaciente[2])); ?>],
                        [<?php echo json_encode(count($allPaciente[3])); ?>],
                        [<?php echo json_encode(count($allPaciente[4])); ?>],
                        [<?php echo json_encode(count($allPaciente[5])); ?>],
                        [<?php echo json_encode(count($allPaciente[6])); ?>],
                        [<?php echo json_encode(count($allPaciente[7])); ?>],
                        [<?php echo json_encode(count($allPaciente[8])); ?>],
                        [<?php echo json_encode(count($allPaciente[9])); ?>],
                        [<?php echo json_encode(count($allPaciente[10])); ?>],
                        [<?php echo json_encode(count($allPaciente[11])); ?>]

                    ],
                    backgroundColor: [
                        "#f7464a"

                    ],
                    borderColor: [
                        "#f7464a"
                    ],
                    borderWidth: 1
                },
                {
                    label: 'Atendidos',
                    data: [
                        [<?php echo json_encode(count($pacientesAtendidos[0])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[1])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[2])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[3])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[4])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[5])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[6])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[7])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[8])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[9])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[10])) ?>],
                        [<?php echo json_encode(count($pacientesAtendidos[11])) ?>]
                    ],
                    backgroundColor: [
                        "#46BFBD"
                    ],
                    borderColor: [
                        "#46BFBD"
                    ],
                    borderWidth: 1
                }]
        },
        options: {
            responsive: true
        },
        scales: {
            yAxes: [{
                    barPercentage: 0.5
                }]
        },
        elements: {
            rectangle: {
                borderSkipped: 'left'
            }
        }
    };
    var ctx = document.getElementById("totalPaciente").getContext('2d');
    window.line = new Chart(ctx, myChart);



    // Sets callbacks to the buttons in the list
//                    refreshCallbacks();
    //    userList.add({ name: 'Leia', born: '1954', image: 'http://www.listjs.com/images/tests/leia.jpeg', id: 5, timestamp: '67893' });


    $(document).ready(function () {

        var localeCode = "pt";

        $.post('<?php echo URL; ?>account/events',
                function (data) {

                    $('#calendar').fullCalendar({
                        header: {
                            left: 'prev,next today',
                            center: 'title',
                            right: 'month,agendaWeek,agendaDay'
                        },
                        buttonText: {
                            today: 'Hoje',
                            month: 'Mês',
                            week: 'Semana',
                            day: 'Dia'
                        },
                        theme: true,
                        themeSystem: 'bootstrap3',
                        locale: localeCode,
                        defaultDate: new Date(),
                        navLinks: true, // can click day/week names to navigate views
                        editable: true,
                        selectable: true,
                        eventLimit: true, // allow "more" link when too many events
                        // selectHelper: true,
                        // allDaySlot: true,
                        eventLimit: true, // allow "more" link when too many events
                                events: $.parseJSON(data),
                        eventDrop: function (event, delta, revertFunc) {

                            var newId = event.id;
                            var newStard = $.fullCalendar.moment(event.start).format();
                            var newEnd = $.fullCalendar.moment(event.end).format();
                            var newTitle = event.title;

                            if (!confirm("Esta seguro??")) {
                                revertFunc();
                            } else {
                                $.post('<?php echo URL; ?>Events/updatEvent',
                                        {
                                            id: newId,
                                            start: newStard,
                                            end: newEnd,
                                            title: newTitle
                                        },
                                function (data) {
                                    if (data == 1) {
                                        alert('Se actualizo correctamente');
                                    }
                                });
                            }
                        },
                        eventResize: function (event, delta, revertFunc) {
                            var newId = event.id;
                            var newStard = $.fullCalendar.moment(event.start).format();
                            var newEnd = $.fullCalendar.moment(event.end).format();
                            var newTitle = event.firstname;



                            if (!confirm("Esta seguro de cambiar la fecha?")) {
                                revertFunc();
                            } else {
                                $.post('<?php echo URL; ?>Events/updatEvent',
                                        {
                                            id: newId,
                                            start: newStard,
                                            end: newEnd,
                                            title: newTitle

                                        },
                                function (data) {
                                    if (data == 1) {
                                        alert('Se cambio correctamente');
                                    }
                                });
                            }
                        },
                        dayClick: function (data, event, view) {

                            $("#modalClick").modal();
                            $(this).css("background", "red");
                        },
                        eventClick: function (event, jsEvent, view) {

                            // alert(event.title);
                            $('#mhdnIdEvento').val(event.id);
                            $('#title').val(event.firstname);
                            $('#nome').html(event.firstname + " " + event.lastname);
                            $('#telefone').html(event.telephone);
                            $('#address_1').html(event.address_1);
                            $('#address_2').html(event.address_2);
                            $('#sexo').html(event.sexo);
                            $('#bairro').html(event.bairro);
                            $('#city').html(event.city);
                            $('#email').html(event.email);
                            $('#infos').html(event.info);
                            $('#id').html(event.usuarios_id);
                            $('#modalEvento').modal();

                            if (event.url) {
                                window.open(event.id);
                                return false;
                            }

                        },
                        eventAfterRender: function (event, element, view) {
                            var dataHoje = new Date();
                            if (event.start < dataHoje && event.end > dataHoje) {
                                //event.color = "#FFB347"; //Em andamento
                                element.css('background-color', '#FFB347');
                            } else if (event.start < dataHoje && event.end < dataHoje) {
                                //event.color = "#77DD77"; //Concluído OK
                                element.css('background-color', '#77DD77');
                            } else if (event.start > dataHoje) {
                                //event.color = "#AEC6CF"; //Não iniciado
                                element.css('background-color', '#AEC6CF');
                            }
                        },
                        eventRender: function (event, element) {
                            var el = element.html();
                            element.html("<div style='width:90%;float:left;'>" + el + "</div>" +
                                    "<div style='color:red;text-align:right;' class='closeE'>" +
                                    "<i class='glyphicon glyphicon-trash tra'></i>" +
                                    "</div>");

                            element.find('.closeE').click(function () {
                                if (!confirm("Esta seguro de eliminar el evento?")) {
                                    return false;
                                } else {
                                    var id = event.Paciente_id;

                                    $.post('<?php echo URL; ?>Events/deleteEvent',
                                            {
                                                Paciente_id: id
                                            },
                                    function (data) {
                                        if (data === 1) {
                                            $('#calendar').fullCalendar('removeEvents', event.Paciente_id);
                                            alert('Se elimino correctamente');
                                        }
                                    });

                                }

                            });
                        }

                    });
                });


// secretaria calendar

        function doSubmit() {
            $("#createEventModal").modal('hide');
            var title = $('#title').val();
            var startTime = $('#startTime').val();
            var endTime = $('#endTime').val();

            $.ajax({
                url: 'index.php',
                data: 'action=add&title=' + title + '&start=' + startTime + '&end=' + endTime,
                type: "POST",
                success: function (json) {
                    $("#calendar").fullCalendar('renderEvent',
                            {
                                id: json.id,
                                title: title,
                                start: startTime,
                                end: endTime,
                            },
                            true);
                }
            });

        }

    });

    $("#save").click(function () {

        var data = $("#cadastroPaciente :input").serializeArray();
        $.post($("#cadastroPaciente").attr("action"), data, function (info) {
            var c = $("result").html(info.info);
            alert(c)
            // clearInfo();
            // hideForm();
            // showSucessMessage();

        });
    });



    var options2 = {
        valueNames: ['id2', 'name2', 'date2', 'consulta2', 'valor2', 'valorP2', 'qualt2'],
        page: 3,
        pagination: true
    };

    // Init list
    var consultListPag = new List('consultListPag', options2);


    var options1 = {
        valueNames: ['id1', 'name1', 'date1', 'titulo1', 'valor1'],
        page: 3,
        pagination: true
    };


    // Init list
    var consultListAgend = new List('consultListAgend', options1);

    var options3 = {
        valueNames: ['id3', 'name3', 'sexo3', 'date3', 'consult3'],
        page: 10,
        pagination: true
    };

    // Init list
    var consultListCadastro = new List('consultListCadastro', options3);


    var options4 = {
        valueNames: ['idretorno', 'nameRetorno', 'sexoRetorno', 'dateRetorno', 'telefoneRetorno'],
        page: 10,
        pagination: false
    };

    // Init list
    var pacientRetorno = new List('consultListCadastroRetorno', options4);


    var options5 = {
        valueNames: ['id4', 'name4', 'titulo4', 'consulta4'],
        page: 10,
        pagination: true
    };

    // Init list
    var pacientFalta = new List('pacientFalta', options5);
    var idField = $('#id-field'),
            nameField = $('#name-field'),
            ageField = $('#age-field'),
            cityField = $('#city-field'),
            addBtn = $('#add-btn'),
            editBtn = $('#edit-btn').hide(),
            removeBtns = $('.remove-item-btn'),
            editBtns = $('.edit-item-btn');


    jQuery.datetimepicker.setLocale('pt');

    jQuery('#datetimepicker').datetimepicker({
    });

</script>

<!-- Modal -->
<div id="createEventModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Event</h4>
            </div>
            <div class="modal-body">
                <div class="control-group">
                    <label class="control-label" for="inputPatient">Event:</label>
                    <div class="field desc">
                        <input class="form-control" id="title" name="title" placeholder="Event" type="text" value="">
                    </div>
                </div>

                <input type="hidden" id="startTime"/>
                <input type="hidden" id="endTime"/>



                <div class="control-group">
                    <label class="control-label" for="when">When:</label>
                    <div class="controls controls-row" id="when" style="margin-top:5px;">
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button type="submit" class="btn btn-primary" id="submitButton">Save</button>
            </div>
        </div>

    </div>
</div>
