<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */
use Ballybran\Helpers\Security\Session;
use Ballybran\Library\Form;

\Module\Clinic\Lib\menu\Sub_Menu::getSubMenu();
?>
<div class="text-center"><h1>ENFERMAGEM</h1></div>

<?php
$register = \Ballybran\Database\RegistryDatabase::getInstance();
$stmt = $register->get("PDO");
?>



<div class="col-sm-12">
    <div class="row ">
        <div class="col-lg-12 cartao" >

            <div class="col-lg-3 4u 12u(mobile)">

                <?php if (!empty($this->UserPhoto['path'])) { ?>

                    <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7  img-responsive img-circle" alt="<?php echo $this->UserPhoto['name']; ?>" />
                <?php } else {
                    ?>
                    <img  src="<?php echo URL . DIR_FILE ?>Public/images/profile-icon.png" class="col-lg-7  img-responsive img-circle" />
                <?php } ?>
            </div>

            <div class="col-lg-3 4u 12u(mobile) text-left">
                <h4>Contacto</h4>

                <strong>Nome: </strong><?php echo $this->user['firstname'] . "\t" . $this->user['lastname']; ?><br>
                <strong>Telefone: </strong><?php echo $this->user['telephone']; ?><br>
                <strong>Email: </strong><?php echo $this->user['email']; ?><br>

            </div>

            <div class="col-lg-3 4u 12u(mobile) text-left">
                <h4>Outras</h4>
                <strong>Sexo: </strong><?php echo $this->user['sexo'] == 'f' ? "Feminino" : "Masculino"; ?><br>
                <strong>Aniversário: </strong><?php echo $this->user['dataNascimento']; ?><br>
                <strong>Perfil: </strong><?php echo $this->user['role']; ?><br>

            </div>
            <div class="col-lg-3 4u 12u(mobile) text-left">
                <h4>Endereço</h4>

                <strong>Endereço 1: </strong><?php echo $this->user['address_1'] ?><br>
                <strong>Endereço 2: </strong><?php echo $this->user['address_2']; ?><br>
                <strong>Cidade: </strong><?php echo $this->user['city']; ?><br>
                <strong>País: </strong><?php echo $this->user['country']; ?><br>
            </div>

        </div>
    </div>
</div>



<div class="col-lg-12 col-sm-6">
    <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <div  id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <div class="hidden-xs">Home</div>
            </div>
        </div>
        <div class="btn-group" role="group">
            <div  id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="icon fa fa-picture-o" aria-hidden="true"></span>
                <div class="hidden-xs">Triagem</div>
            </div>
        </div>
        <div class="btn-group" role="group">
            <div  id="stars" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="icon icon fa-cog" aria-hidden="true"></span>
                <div class="hidden-xs">Configurações</div>
            </div>
        </div>
        <div class="btn-group" role="group">
            <div  id="agenda" class="btn btn-default" href="#tab4" data-toggle="tab"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                <div class="hidden-xs">Agenda</div>
            </div>
        </div>

    </div>

    <div class="panel panel-info col-sm-12">
        <div class="tab-content">
            <div class="tab-pane fade in active" id="tab1">
                <br><br>

            </div>


            <div class="tab-pane fade in" id="tab2">

                <br>
                <h3>triagem</h3>


                <!-- Tab panes -->

                <div id="triagem">
                    <input type="text" class="search form-control" placeholder="Pesquisar Candidatos"  />
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="sort" data-sort="name1">Name Completo </th>
                                <th class="sort" data-sort="date1">idade</th>

                            </tr>
                        </thead>
                        <tbody class="list">

                            <?php foreach ($this->pacienteMedico as $key => $pacienteMedico) : ?>
                                <tr>
                                    <td class="id" style="display:none;"><?php echo $key['id'] + 1; ?></td>
                                    <td class="name1"><?php echo $pacienteMedico['firstname'] . "\t" . $pacienteMedico['lastname']; ?></td>
                                    <td class="date1"><?php echo (intval(\Ballybran\Helpers\Time\Timestamp::dataTime('Y')) - intval($pacienteMedico['dataNascimento']) ); ?></td>

                                    <td> <b class="btn btn-primary" data-toggle="modal" data-target="#triagem-<?php echo $pacienteMedico['id']; ?>">Triagem</b></td>
                                </tr>

                                <!-- modal triagem -->

                            <div class="modal fade" id="triagem-<?php echo $pacienteMedico['id']; ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Triagem do Paciente: <?php echo $pacienteMedico['firstname'] . "\t" . $pacienteMedico['lastname']; ?></h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">


                                            <form  method="post" action="<?php echo URL; ?>Secretaria/insertExameFisico">
                                                <div class="row">
                                                    <div class="col-md-5">
                                                        <input type="hidden" name="Paciente_id" value="<?php echo $pacienteMedico['id']; ?>">

                                                        <select class="form-control"  name="Funcionarios_id"  id="exampleFormControlSelect2">
                                                            <?php
                                                            $medicos = $stmt->selectManager("SELECT    usuarios.firstname, Funcionarios.id FROM Funcionarios INNER JOIN Especialidade ON Especialidade.id = Funcionarios.Especialidade_id INNER JOIN usuarios ON usuarios.id = Funcionarios.usuarios_id     INNER JOIN Paciente ON Paciente.Especialidade_id = Especialidade.id WHERE Paciente.id = " . $pacienteMedico['id']);
                                                            ?>

                                                            <option>--</option>

                                                            <?php
                                                            foreach ($medicos as $keys => $val) :


                                                                $count = $stmt->selectManager("SELECT COUNT(Paciente.id) FROM Paciente LEFT OUTER JOIN Anamnese on Paciente.id = Anamnese.Paciente_id  INNER JOIN Func_has_Paci on  Paciente.id = Func_has_Paci.Paciente_id INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id WHERE  Anamnese.Funcionarios_id is null AND Funcionarios.usuarios_id = " . $val['id'])[0];
                                                                foreach ($count as $key => $counts) {
                                                                    ?>

                                                                    <option value="<?php echo $val['id']; ?>"><?php echo $val['firstname'] . "\t|\t n de pacientes ({$counts})"; ?> </option>

                                                                <?php } endForeach; ?>

                                                        </select>
                                                    </div>
                                                    <div class="form-group">
                                                        <label>Altura </label>
                                                        <input type="text" class="form-control" name="altura"> m
                                                    </div>
                                                </div>
                                                <div class="col-md-3">
                                                    <div class="form-group">
                                                        <label>Peso</label>
                                                        <input type="text" class="form-control" name="peso"> Kg
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label>Frequência Cardiaca</label>
                                                        <input type="text" class="form-control" name="freq_cardiaca" > Batimentos por minutos
                                                    </div>
                                                </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Pressão Arterial Sitótelica</label>
                                                    <input type="text" class="form-control" name="press_arte_sistolica"> mmHg
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Pressão Arterial Diastótelica</label>
                                                    <input type="text" class="form-control" name="press_arte_diastolica"/> mmHg
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Observações Gerais</label>
                                                    <!--                                                                    <input  name="Funcionarios_id" value="--><?php //echo $this->paciente['Funcionarios_id'];                 ?><!--" type="hidden" />-->
                                                    <textarea rows="5" name="obs_gerais" class="form-control"></textarea>
                                                    <!--                                                                    <input type="hidden" class="form-control" name="Paciente_id" value="--><?php //echo $this->paciente['Paciente_id'];                ?><!--">-->
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                        <button type="submit" class="btn btn-primary">Enviar triagem</button>
                                    </div>
                                    <div class="clearfix"></div>

                                    </form>

                                </div>
                            </div>
                            <!-- end modal triagem -->


                        <?php endforeach; ?>

                        </tbody>
                    </table>
                </div>




            </div>


            <div class="tab-pane fade in" id="tab3">

                <br><br><br>

                <div class="row" style="min-height:300px;">
                    <div  class="col-lg-12">
                        <div class="col-xs-8">
                            <!-- required for floating -->
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs ">
                                <li class="active"><a href="#home" data-toggle="tab">Dados Pessoais</a></li>
                                <li><a href="#info" data-toggle="tab">Atualizar dados</a></li>
                                <li><a href="#password" data-toggle="tab">Password</a></li>
                            </ul>
                        </div>
                        <div class="col-xs-9">
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div class="tab-pane active" id="home">
                                    <br><br><br>

                                    <div class="row">

                                        <div class="panel panel-info col-lg-12" >
                                            <div class="panel-heading">
                                                <h3 class="panel-title">Meus Dados</h3>
                                            </div>
                                            <div class="panel-body">
                                                <div class="row">

                                                    <div class=" col-md-9 col-lg-9 ">
                                                        <div class="col-lg-7 4u 12u(mobile)">

                                                            <?php if (!empty($this->UserPhoto['path'])) { ?>

                                                                <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7  img-responsive img-circle" alt="<?php echo $this->UserPhoto['name']; ?>" />
                                                                <?php
                                                                if (Session::exist()) {
                                                                    ?>
                                                                    <a href="<?php echo URL; ?>account/deleteImage"  class="glyphicon glyphicon-remove" >delete</a>
                                                                    <?php
                                                                }
                                                            } else {
                                                                ?>
                                                                <img  src="<?php echo URL . DIR_FILE ?>Public/images/profile-icon.png" class="col-lg-7  img-responsive img-circle" />
                                                            <?php } ?>
                                                        </div>
                                                        <br>
                                                        <table class="table table-user-information">
                                                            <tbody>
                                                                <tr>
                                                                    <td>Especialidade:</td>
                                                                    <td><?php echo $this->user['telephone']; ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Contratado em::</td>
                                                                    <td><?php echo $this->user['createTime']; ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Data de Nascimento</td>
                                                                    <td><?php echo $this->user['dataNascimento']; ?></td>
                                                                </tr>

                                                                <tr>
                                                                <tr>
                                                                    <td>Genero</td>

                                                                    <td>
                                                                        <?php echo $this->user['sexo'] != "" ? $this->user['sexo'] == 'f' ? "Feminino" : "Masculino" : "Nao inserido"; ?>
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Endereço</td>
                                                                    <td><?php echo $this->user['address_1']; ?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Email</td>
                                                                    <td><a href="mailto:<?php echo $this->user['email']; ?>"><?php echo $this->user['email']; ?></a></td>
                                                                </tr>
                                                            <td>Numero do Telefone</td>
                                                            <td><?php echo $this->user['telephone']; ?><br><br><?php echo $this->user['telephone2']; ?>(Mobile)
                                                            </td>

                                                            </tr>

                                                            </tbody>
                                                        </table>

                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                    <!-- profile end -->

                                </div>
                                <div class="tab-pane" id="info">
                                    <br><br>
                                    <form method="post" action="<?php echo URL; ?>account/insertImageUser" enctype="multipart/form-data">
                                        <label for="pic">Faça o Uploads de uma foto para o perfil:</label>
                                        <input type="file" name="archive[]" id="pic" />
                                        <label for="colorWell">Qualidade:</label>
                                        <input type="number" value="50" name="quality"/>
                                        <label for="colorWell">Rotação:</label>
                                        <input type="number"  value="00" name="degree" />
                                        <label for="colorWell">Color:</label>
                                        <input type="color" name="color" value="#ff0000" class="contact-form" id="colorWell" />
                                        <input type="submit" value="Carregar" />
                                    </form>

                                    <h4>My Account</h4>


                                    <?php
                                    echo Form::open(['method' => 'post', 'action' => URL . 'account/updates', 'name' => '', 'class' => 'form-signin', 'style' => 'width:50%']);
                                    ?>

                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">First Name</label>
                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'firstname', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['firstname']]);
                                        ?>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Last Name</label>
                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'lastname', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['lastname']]);
                                        ?>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">User Name</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'username', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['username']]);
                                        ?>

                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">E-mail</label>

                                        <?php
                                        echo Form::input(['type' => 'email', 'name' => 'email', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['email']]);
                                        ?>

                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Data de Nascimento</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'dataNascimento', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['dataNascimento']]);
                                        ?>

                                    </div>
                                    <small>Your Address</small>
                                    <hr>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Telephone</label>
                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'telephone', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['telephone']]);
                                        ?>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Company</label>
                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'company', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['company']]);
                                        ?>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Address 1</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'address_1', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['address_1']]);
                                        ?>

                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Address 2</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'address_2', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['address_2']]);
                                        ?>

                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Bairro</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'bairro', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['bairro']]);
                                        ?>

                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Post Code</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'postcode', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['postcode']]);
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">City</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'city', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['city']]);
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Country</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'country', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['country']]);
                                        ?>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Region/State</label>

                                        <?php
                                        echo Form::input(['type' => 'text', 'name' => 'zone', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['zone']]);
                                        ?>

                                    </div>
                                    <?php
                                    echo Form::input(['type' => 'hidden', 'name' => 'id', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['id']]);
                                    ?>



                                    <div class="form-group">
                                        <br/>
                                        <button class="btn btn-primary btn-inverse btn-default" onclick="updateUser(<?php echo $this->user['id']; ?>)" ><p class="glyphicon glyphicon-refresh "></p></button>
                                        <a class="btn btn-danger deletar" href="<?php echo URL ?>account/deletes/<?php echo $this->user['id']; ?>"><p class="glyphicon glyphicon-trash "></p></a>

                                    </div>

                                    <?php
                                    echo Form::close();
                                    ?>
                                </div>
                                <div class="tab-pane" id="password">
                                    <br><br>
                                    <section>

                                        <div class="row">
                                            <form  class="form-horizontal" action="<?php echo URL; ?>account/managePassword" name="perfil" method="post">

                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">Password</label>
                                                    <input type="password" class="form-control" placeholder="Senha antiga" name="oldPassword" id="exampleInputPassword1">
                                                    <br>
                                                </div>
                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">Password</label>
                                                    <input type="password" class="form-control" placeholder="Senha Nova" name="password" id="exampleInputPassword1">
                                                    <input type="hidden" class="form-control" name="id" value="<?php echo $this->user['id']; ?>"  id="exampleInputPassword1">
                                                    <br>
                                                </div>
                                                <div class="col-sm-8">
                                                    <button type="submit" class="btn btn-info">Atualizar</button>
                                                </div>

                                            </form>
                                        </div>
                                    </section>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div><!--- end tabe -->
            </div>
            <div class="tab-pane fade in" id="tab4">

                <h3>4</h3>

            </div>

        </div>
    </div>
</div>
</div>


<script>
    var options1 = {
        valueNames: ['id1', 'name1', 'date1', 'numero1', 'idade1']
    };

    // Init list
    var consultListAgend = new List('triagem', options1);


    $('.bd-example-modal-turma').data('bs.modal').handleUpdate();
</script>
