<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

use Ballybran\Helpers\Security\Session;
use Module\Clinic\Lib\menu\Sub_Menu;


use Ballybran\Library\Form;

$c = new \Ballybran\Core\Caller\Caller('Module\Lib\Visitor', 'contagem');
$d = $c->__init();

$register = \Ballybran\Database\RegistryDatabase::getInstance();
$stmt =  $register->get("PDO");
$novos = $stmt->selectManager("SELECT * FROM usuarios LEFT OUTER JOIN Paciente ON usuarios.id = Paciente.usuarios_id WHERE Paciente.usuarios_id is null AND  usuarios.role = 'paciente' ");
$atendidos = $stmt->selectManager("SELECT * FROM Paciente INNER JOIN usuarios ON usuarios.id= Paciente.usuarios_id
                                                                    INNER JOIN Func_has_Paci ON Func_has_Paci.Paciente_id = Paciente.id
                                                                    INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id
                                                                    INNER JOIN Convenio ON Convenio.id = Paciente.Convenio_id 
                                                                    INNER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id AND Anamnese.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Docum_Atestado ON Docum_Atestado.Paciente_id = Paciente.id AND Docum_Atestado.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Evolucao ON Evolucao.Paciente_id = Paciente.id AND Evolucao.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Exame_Fisico ON Exame_Fisico.Paciente_id = Paciente.id AND Exame_Fisico.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN hipotese_diagnostica ON hipotese_diagnostica.Paciente_id = Paciente.id AND hipotese_diagnostica.Funcionarios_id = Funcionarios.id
                                                                    LEFT OUTER JOIN Medicamento ON Medicamento.Paciente_id = Paciente.id ");

$emEspera =  $stmt->selectManager("SELECT  Paciente.*, Func_has_Paci.* FROM  Paciente LEFT OUTER JOIN Func_has_Paci on  Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id WHERE Func_has_Paci.funcionarios_id IS NULL"  );
$agendados =  $stmt->selectManager(" SELECT * FROM Paciente LEFT OUTER JOIN Anamnese on Paciente.id = Anamnese.Paciente_id  INNER JOIN Func_has_Paci on  Paciente.id = Func_has_Paci.Paciente_id INNER JOIN Funcionarios ON Funcionarios.id = Func_has_Paci.Funcionarios_id WHERE  Anamnese.Paciente_id is NULL ") ;

$mulher = $stmt->selectManager("SELECT * FROM Anamnese INNER JOIN Paciente ON Paciente.id = Anamnese.Paciente_id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id WHERE usuarios.sexo = 'f' ");
$homem = $stmt->selectManager("SELECT * FROM Anamnese INNER JOIN Paciente ON Paciente.id = Anamnese.Paciente_id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id WHERE usuarios.sexo = 'm' ");

$allPaciente[0] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 0+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[1] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 1+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[2] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 2+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[3] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 3+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[4] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 4+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[5] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 5+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[6] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 6+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[7] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 7+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[8] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 8+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[9] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 9+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[10] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 10+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");
$allPaciente[11] = $stmt->selectManager("SELECT DATE_FORMAT(Paciente.create_dt, '%m') FROM Paciente  INNER JOIN Funcionarios INNER JOIN Func_has_Paci on Funcionarios.id = Func_has_Paci.Funcionarios_id AND Paciente.id = Func_has_Paci.Paciente_id LEFT OUTER JOIN Anamnese ON Anamnese.Paciente_id = Paciente.id  WHERE Anamnese.Funcionarios_id is null  and DATE_FORMAT(Func_has_Paci.Func_dt, '%m') = 11+1 AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017");

$pacientesAtendidos[0] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 0+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[1] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 1+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[2] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 2+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[3] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 3+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[4] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 4+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[5] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 5+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[6] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 6+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[7] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 7+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[8] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 8+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[9] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 9+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[10] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 10+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");
$pacientesAtendidos[11] = $stmt->selectManager("SELECT DATE_FORMAT(Anamnese.data, '%m')  FROM Anamnese INNER JOIN Paciente on Anamnese.Paciente_id = Paciente.id INNER JOIN Func_has_Paci on Func_has_Paci.Paciente_id = Paciente.id INNER JOIN Funcionarios on Func_has_Paci.Funcionarios_id = Funcionarios.id WHERE DATE_FORMAT(Anamnese.data, '%m') = 11+1  AND  DATE_FORMAT(Anamnese.data, '%Y') = 2017 AND Func_has_Paci.funcionarios_id ");

$naoAtendidos2 =  $stmt->selectManager("SELECT Func_has_Paci.*, Paciente.*, Func_has_Paci.* , usuarios.* FROM Func_has_Paci INNER JOIN Paciente INNER JOIN Funcionarios ON Func_has_Paci.Funcionarios_id = Funcionarios.id AND Func_has_Paci.Paciente_id = Paciente.id INNER JOIN usuarios ON usuarios.id = Paciente.usuarios_id LEFT OUTER JOIN Medicamento ON Medicamento.Paciente_id = Paciente.id  WHERE Medicamento.Funcionarios_id "  );

$medicos =  $stmt->selectManager("SELECT usuarios.* FROM usuarios WHERE usuarios.role = 'funcionario' "  );
$laboratorio =  $stmt->selectManager("SELECT  usuarios.* FROM usuarios WHERE usuarios.role = 'laboratorio' "  );
$secretaria =  $stmt->selectManager("SELECT  usuarios.* FROM usuarios WHERE usuarios.role = 'secretaria' "  );
$enfermeiros =  $stmt->selectManager("SELECT  usuarios.* FROM usuarios WHERE usuarios.role = 'enfermeiro' "  );


?>


    <?php Sub_Menu::getSubMenu(); ?>

    <div class="col-sm-12">

        <div class="row ">
                <div class="col-lg-3 4u 12u(mobile)">

                    <?php if (!empty($this->UserPhoto['path'])) { ?>

                        <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7  img-responsive img-circle" alt="<?php echo $this->UserPhoto['name']; ?>" />
                        <?php

                    } else {?>
                        <img  src="<?php echo URL . DIR_FILE?>Public/images/profile-icon.png" class="col-lg-7  img-responsive img-circle" />
                    <?php } ?>
                </div>

                <div class="col-lg-3 4u 12u(mobile) text-left">
                    <h4>Contacto</h4>

                    <strong>Nome: </strong><?php echo  $this->user['firstname'] . "\t" .  $this->user['lastname']; ?><br>
                    <strong>Telefone: </strong><?php echo  $this->user['telephone']; ?><br>
                    <strong>Email: </strong><?php echo  $this->user['email']; ?><br>

                </div>

                <div class="col-lg-3 4u 12u(mobile) text-left">
                    <h4>Outras</h4>
                    <strong>Sexo: </strong><?php echo  $this->user['sexo'] == 'f' ? "Feminino" : "Masculino"; ?><br>
                    <strong>Aniversário: </strong><?php echo  $this->user['dataNascimento']; ?><br>
                    <strong>Perfil: </strong><?php echo  $this->user['role']; ?><br>

                </div>
                <div class="col-lg-3 4u 12u(mobile) text-left">
                    <h4>Endereço</h4>

                    <strong>Endereço 1: </strong><?php echo  $this->user['address_1'] ?><br>
                    <strong>Endereço 2: </strong><?php echo  $this->user['address_2']; ?><br>
                    <strong>Cidade: </strong><?php echo  $this->user['city']; ?><br>
                    <strong>País: </strong><?php echo  $this->user['country']; ?><br>
                </div>

        </div>
    </div>

    <div class="col-lg-12 col-sm-12">
        <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
            <div class="btn-group" role="group">
                <div  id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    <div class="hidden-xs">Painel</div>
                </div>
            </div>
            <div class="btn-group" role="group">
                <div  id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="icon icon fa-user" aria-hidden="true"></span>
                    <div class="hidden-xs">Funcionarios</div>
                </div>
            </div>
            <div class="btn-group" role="group">
                <div  id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    <div class="hidden-xs">Pacientes</div>
                </div>
            </div>
            <div class="btn-group" role="group">
                <div  id="stars" class="btn btn-primary" href="#tab4" data-toggle="tab"><span class="icon icon fa-cog" aria-hidden="true"></span>
                    <div class="hidden-xs">Configurações</div>
                </div>
            </div>
            <div class="btn-group" role="group">
                <div  id="favorites" class="btn btn-default" href="#tab5" data-toggle="tab"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                    <div class="hidden-xs">Historico</div>
                </div>
            </div>
        </div>

        <div class="panel panel-info col-lg-12">
            <div class="tab-content">
                <div class="tab-pane fade in active" id="tab1">
                <br><br>
                   <!--- blocos de contagem-->
                        <div class="row">
                            <div class="col-lg-2 col-sm-6">
                                <div class="circle-tile ">
                                    <a href="#"><div class="circle-tile-heading dark-blue"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                    <div class="circle-tile-content dark-blue">
                                        <div class="circle-tile-description text-faded"> Novos sem consulta</div>
                                        <div class="circle-tile-number text-faded "> <?php echo count($novos);?></div>
                                    </div>
                                </div>
                            </div>

                                <div class="col-lg-2 col-sm-6">
                                    <div class="circle-tile ">
                                        <a href="#"><div class="circle-tile-heading dark-orange"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                        <div class="circle-tile-content dark-orange">
                                            <div class="circle-tile-description text-faded"> Em Espera </div>
                                            <div class="circle-tile-number text-faded "> <?php echo count($emEspera);?></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-sm-6">
                                    <div class="circle-tile ">
                                        <a href="#"><div class="circle-tile-heading dark-success"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                        <div class="circle-tile-content dark-success">
                                            <div class="circle-tile-description text-faded"> Agendados</div>
                                            <div class="circle-tile-number text-faded "><?php echo count($agendados);?></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-2 col-sm-6">
                                    <div class="circle-tile ">
                                        <a href="#"><div class="circle-tile-heading dark-red"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
                                        <div class="circle-tile-content dark-red">
                                            <div class="circle-tile-description text-faded"> Atendidos </div>
                                            <div class="circle-tile-number text-faded "><?php echo count($atendidos);?></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                    <div class="row ">


                        <div class="col-lg-4 u4 12u(mobile)">
                            <div class="card">

                                <div class="header">
                                    <h5 class="titles">Estatisticas de Pacientes</h5>
                                </div>
                                <div class="content">

                                    <canvas id="barChart"  width="600" height="400"></canvas>

                                    <div class="footer">
                                        <div class="legend">

                                        </div>
                                        <hr>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end -->


                        <div class="col-lg-4 4u 12u(mobile)">
                            <div class="card">

                                <div class="header">
                                    <h5 class="titles">Estatisticas de Funcionarios</h5>
                                </div>
                                <div class="content">
                                    <canvas id="barChartFunc"  width="600" height="400"></canvas>

                                    <div class="footer">
                                        <div class="legend">
                                        </div>
                                        <hr>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end -->
                        <div class="col-lg-4 u4 12u(mobile)">
                                <div class="card">

                                        <div class="header">
                                            <h5 class="titles">Estatisticas de Paciente Por Sexo</h5>
                                        </div>
                                        <div class="content">

                                            <canvas id="barSexo"  width="600" height="400"></canvas>

                                            <div class="footer">
                                                <div class="legend">
                                                </div>
                                                <hr>
                                            </div>
                                        </div>
                                    </div>
                            </div> <!-- end -->

                        <div class="col-md-12">
                            <div class="card">
                                <div class="header">
                                        <div id="calendar"></div>



                                                <!-- Modal -->
                                                <div id="createEventModal" class="modal fade" role="dialog">
                                                    <div class="modal-dialog">

                                                        <!-- Modal content-->
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                <h4 class="modal-title">Add Event</h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <div class="control-group">
                                                                    <label class="control-label" for="inputPatient">Event:</label>
                                                                    <div class="field desc">
                                                                        <input class="form-control" id="title" name="title" placeholder="Event" type="text" value="">
                                                                    </div>
                                                                </div>

                                                                <input type="hidden" id="startTime"/>
                                                                <input type="hidden" id="endTime"/>



                                                                <div class="control-group">
                                                                    <label class="control-label" for="when">When:</label>
                                                                    <div class="controls controls-row" id="when" style="margin-top:5px;">
                                                                    </div>
                                                                </div>

                                                            </div>
                                                            <div class="modal-footer">
                                                                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                                                                <button type="submit" class="btn btn-primary" id="submitButton">Save</button>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>


                                                <div id="calendarModal" class="modal fade">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                                <h4 class="modal-title">Event Details</h4>
                                                            </div>
                                                            <div id="modalBody" class="modal-body">
                                                                <h4 id="modalTitle" class="modal-title"></h4>
                                                                <div id="modalWhen" style="margin-top:5px;"></div>
                                                            </div>
                                                            <input type="hidden" id="eventID"/>
                                                            <div class="modal-footer">
                                                                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                                                                <button type="submit" class="btn btn-danger" id="deleteButton">Delete</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!--Modal-->






                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="card">
                                <div class="header">
                                    <h5 class="titles">Estatistica Mensal de Pciente</h5>
                                    <p class="category">24 Hours performance</p>
                                </div>
                                <div class="content">

                                    <canvas id="totalPaciente" class="ct-chart"></canvas>

                                    <div class="footer">
                                        <div class="legend">
                                        </div>
                                        <hr>

                                    </div>
                                </div>
                            </div>
                        </div><!-- end -->

                        <div class="col-lg-12">
                            <div class="card">
                                <div class="header">
                                    <h4 class="titles">Estatistica de Funcionario</h4>
                                    <p class="category">24 Hours performance</p>
                                </div>
                                <div class="content">
                                    <canvas id="totalFunc" class="ct-chart"></canvas>
                                    <div class="footer">
                                        <div class="legend">

                                        </div>
                                        <hr>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end -->

                        <div class="col-md-6">
                            <div class="card ">
                                <div class="header">
                                    <h4 class="title">Atividades da Clinica em Tempo real</h4>
                                    <p class="category">All products including Taxes</p>
                                </div>
                                <div class="content">
                                    <div id="chartActivity" class="ct-chart"></div>

                                    <div class="footer">
                                        <div class="legend">
                                        </div>
                                        <hr>
                                        <div class="stats">
                                            <i class="fa fa-check"></i> Data information certified
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end -->

                    </div>
                </div>

                <div class="tab-pane fade in" id="tab2">
                    <br>

                    <div class="row" style="min-height:300px;">
                        <div class="col-lg-12 4u 12u(mobile)">

                            <div class="col-xs-8">
                                <!-- required for floating -->
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs tabs-left">
                                    <li class="active"><a href="#Listfunc" data-toggle="tab">Lista  de funcionarios</a></li>
                                    <li><a href="#addFunc" data-toggle="tab" class="glyphicon glyphicon-user ">Novo Funcionario</a></li>
                                    <li><a href="#messages" data-toggle="tab"></a></li>
                                    <li><a href="#settings" data-toggle="tab"></a></li>
                                </ul>
                            </div>
                            <div class="col-xs-12">
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div class="tab-pane active" id="Listfunc">
                                        <a href="<?php echo URL;?>account/printlistfuncionario" class="btn btn-success" target="_blank">Imprimir Lista</a>

                                        <div id="funclist">
                                                <input type="text" class="search form-control" placeholder="Search contact"  />
                                                <table class="table table-bordered">
                                                    <thead>
                                                    <tr>
                                                        <th class="sort" data-sort="name">Name </th>
                                                        <th class="sort" data-sort="date">data do Contrato</th>
                                                        <th class="sort" data-sort="especialidade">Especialidade</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody class="list">

                                                    <?php foreach ($this->userAdmin as $item => $passienteSecretaria) {?>
                                                        <tr>
                                                            <td class="id" style="display:none;"><?php echo $item['id']+1;?></td>
                                                            <td class="name"><?php echo $passienteSecretaria['firstname'] . "\t" .  $passienteSecretaria['lastname'];?></td>
                                                            <td class="date"><?php echo $passienteSecretaria['create_time'];?></td>
                                                            <td class="especialidade"><?php echo $passienteSecretaria['espNome'];?></td>
                                                        </tr>
                                                    <?php } ?>

                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>

                                    <div class="tab-pane" id="addFunc">

                                        <?php
                                        echo Form::open(['method' => 'post', 'action' => URL . 'User/signUp', 'files' => 'enctype=multipart/form-data', 'name' => 'signUp', 'class' => 'form-signin', 'style' => 'width:60%;']);
                                        ?>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Nome</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'firstname', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Nome Completo']);
                                            ?>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Sobrenome</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'lastname', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Nome Completo']);
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Username</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'username', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'user name']);
                                            ?>

                                        </div>
                                        <div class="form-group">

                                            <select name="sexo" id="">
                                                <option value="f">Feminino</option>
                                                <option value="m">Masculino</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Email</label>

                                            <?php
                                            echo Form::input(['type' => 'email', 'name' => 'email', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'email']);
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Password</label>

                                            <?php
                                            echo Form::input(['type' => 'password', 'name' => 'password', 'class' => 'form-control', 'id' => 'user-name', 'placeholder' => 'Password']);
                                            ?>
                                        </div>

                                        <?php
                                        echo Form::button(['type' => 'submit', 'class' => 'form-button-submit button', 'id' => 'send_request', 'value' => 'Cadastrar']);
                                        ?>

                                        <?php
                                        echo Form::close();
                                        ?>

                                    </div>
                                    <div class="tab-pane" id="messages">message Tab.</div>
                                    <div class="tab-pane" id="settings">Settings Tab.</div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>

                </div>
                <div class="tab-pane fade in" id="tab3">
                    <br>

                    <div class="row" style="min-height:300px;">
                        <div  class="col-sm-12">
                            <div class="col-xs-6">
                                <!-- required for floating -->
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs tabs-left">
                                    <li class="active"><a href="#func" data-toggle="tab">Lista  de Pacientes</a></li>
<!--                                    <li><a href="#profile1" data-toggle="tab">Profile</a></li>-->
<!--                                    <li><a href="#messages2" data-toggle="tab">Messages</a></li>-->
<!--                                    <li><a href="#settings3" data-toggle="tab">Settings</a></li>-->
                                </ul>
                            </div>
                            <div class="col-xs-12">
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div class="tab-pane active" id="func">

                                        <div id="pacilist">
                                            <input type="text" class="search form-control" placeholder="Search Paciente"  />
                                            <table class="table table-bordered">
                                                <thead>
                                                <tr>
                                                    <th class="sort" data-sort="name1">Name </th>
                                                    <th class="sort" data-sort="aria1">Especialidade</th>
                                                    <th class="sort" data-sort="date1">data do Pagamento</th>
                                                    <th class="sort" data-sort="status1">Estatus</th>
                                                    <th class="sort" data-sort="medico1">Médico</th>
                                                </tr>
                                                </thead>
                                                <tbody class="list">

                                                <?php foreach ($this->allPaciente as $item => $allPacientes) {?>
                                                    <tr>
                                                        <td class="id" style="display:none;"><?php echo $item['id']+1;?></td>
                                                        <td class="name1"><?php echo $allPacientes['firstname'] . "\t" .  $allPacientes['lastname'];?></td>
                                                        <td class="aria1"><?php echo $allPacientes['espNome'];?></td>
                                                        <td class="date1"><?php echo $allPacientes['dtPag'];?></td>
                                                        <td class="status1"><?php echo $allPacientes['situ_nome'];?></td>
                                                        <td class="medico1"><?php echo $allPacientes['titulo'];?></td>
                                                    </tr>
                                                <?php } ?>

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>

<!--                                    <div class="tab-pane" id="profile1">Profile Tab.</div>-->
<!--                                    <div class="tab-pane" id="messages2">Messages Tab.</div>-->
<!--                                    <div class="tab-pane" id="settings3">Settings Tab.</div>-->
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade in" id="tab4">
                    <br>

                    <div class="row" style="min-height:300px;">
                        <div  class="col-lg-12">
                            <div class="col-xs-8">
                                <!-- required for floating -->
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs tabs-left">
                                    <li class="active"><a href="#home" data-toggle="tab">Dados Pessoais</a></li>
                                    <li><a href="#info" data-toggle="tab">Atualizar dados</a></li>
                                    <li><a href="#password" data-toggle="tab">Password</a></li>
                                </ul>
                            </div>
                            <div class="col-xs-9">
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div class="tab-pane active" id="home">
                                        <br><br><br>

                                        <div class="row">

                                            <div class="panel panel-info col-lg-12" >
                                                <div class="panel-heading">
                                                    <h3 class="panel-title">Meus Dados</h3>
                                                </div>
                                                <div class="panel-body">
                                                    <div class="row">

                                                        <div class=" col-md-9 col-lg-9 ">
                                                            <div class="col-lg-7 4u 12u(mobile)">

                                                                <?php if (!empty($this->UserPhoto['path'])) { ?>

                                                                    <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7 image img-responsive img-thumbnail" alt="<?php echo $this->UserPhoto['name']; ?>" />
                                                                    <?php
                                                                    if (Session::exist()) {
                                                                        ?>
                                                                        <a href="<?php echo URL; ?>account/deleteImage"  class="glyphicon glyphicon-remove" >delete</a>
                                                                        <?php

                                                                    }
                                                                } else {?>
                                                                    <img  src="<?php echo URL . DIR_FILE?>Public/images/profile-icon.png" class="col-lg-7  img-responsive img-circle"  />
                                                                <?php } ?>
                                                            </div>
                                                            <br>
                                                            <table class="table table-user-information">
                                                                <tbody>
                                                                <tr>
                                                                    <td>Especialidade:</td>
                                                                    <td><?php echo "";?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Contratado em::</td>
                                                                    <td><?php echo $this->user['create_time'];?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Data de Nascimento</td>
                                                                    <td><?php echo $this->user['dataNascimento'];?></td>
                                                                </tr>

                                                                <tr>
                                                                <tr>
                                                                    <td>Genero</td>

                                                                    <td>
                                                                        <?php  echo $this->user['sexo'] != "" ?  $this->user['sexo'] == 'f' ? "Feminino" : "Masculino" : "Nao inserido";?>
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Endereço</td>
                                                                    <td><?php echo $this->user['address_1'];?></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Email</td>
                                                                    <td><a href="mailto:<?php echo $this->user['email'];?>"><?php echo $this->user['email'];?></a></td>
                                                                </tr>
                                                                <td>Numero do Telefone</td>
                                                                <td><?php echo $this->user['telephone'];?><br><br><?php echo $this->user['telephone2'];?>(Mobile)
                                                                </td>

                                                                </tr>

                                                                </tbody>
                                                            </table>

                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                        <!-- profile end -->

                                    </div>
                                    <div class="tab-pane" id="info">
                                        <br><br>
                                        <form method="post" action="<?php echo URL; ?>account/insertImageUser" enctype="multipart/form-data">
                                            <label for="pic">Faça o Uploads de uma foto para o perfil:</label>
                                            <input type="file" name="archive[]" id="pic" />
                                            <label for="colorWell">Qualidade:</label>
                                            <input type="number" value="50" name="quality"/>
                                            <label for="colorWell">Rotação:</label>
                                            <input type="number"  value="00" name="degree" />
                                            <label for="colorWell">Color:</label>
                                            <input type="color" name="color" value="#ff0000" class="contact-form" id="colorWell" />
                                            <input type="submit" value="Carregar" />
                                        </form>

                                        <h4>My Account</h4>


                                        <?php
                                        echo Form::open(['method' => 'post', 'action'=> URL .'account/updates', 'name' => '', 'class' => 'form-signin', 'style' => 'width:50%']);
                                        ?>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">First Name</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'firstname', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['firstname']]);
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Last Name</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'lastname', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['lastname']]);
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">User Name</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'username', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['username']]);
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">E-mail</label>

                                            <?php
                                            echo Form::input(['type' => 'email', 'name' => 'email', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['email']]);
                                            ?>


                                        </div>
                                    <div class="form-group">
                                        <label class="control-label" for="input-firstname">Data de Nascimento</label>

                                        <?php
                                        echo Form::input(['type' => 'date', 'name' => 'dataNascimento', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['dataNascimento']]);
                                        ?>
                                    </div>


                                    <small>Your Address</small>
                                        <hr>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Telephone</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'telephone', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['telephone']]);
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Company</label>
                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'company', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['company']]);
                                            ?>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Address 1</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'address_1', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['address_1']]);
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Address 2</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'address_2', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['address_2']]);
                                            ?>

                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Post Code</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'postcode', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['postcode']]);
                                            ?>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">City</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'city', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['city']]);
                                            ?>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Country</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'country', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['country']]);
                                            ?>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label" for="input-firstname">Region/State</label>

                                            <?php
                                            echo Form::input(['type' => 'text', 'name' => 'zone', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['zone']]);
                                            ?>

                                        </div>
                                        <?php
                                        echo Form::input(['type' => 'hidden', 'name' => 'id', 'class' => 'form-control', 'id' => 'user-name', 'value' => $this->user['id']]);
                                        ?>


                                        <div class="form-group">
                                            <br/>
                                            <button class="btn btn-primary btn-inverse btn-default" onclick="updateUser(<?php echo $this->user['id']; ?>)" ><p class="glyphicon glyphicon-refresh "></p></button>
                                            <a class="btn btn-danger deletar" href="<?php echo URL ?>account/deletes/<?php echo $this->user['id']; ?>"><p class="glyphicon glyphicon-trash "></p></a>

                                        </div>

                                        <?php
                                        echo Form::close();
                                        ?>
                                    </div>
                                    <div class="tab-pane" id="password">
                                                                <br><br>
                                        <section>

                                                <div class="row">
                                                        <form  class="form-horizontal" action="<?php echo URL; ?>account/managePassword" name="perfil" method="post">

                                                            <div class="form-group">
                                                                <label for="exampleInputPassword1">Password</label>
                                                                <input type="password" class="form-control" placeholder="Senha antiga" name="password2" id="exampleInputPassword1">
                                                                <br>
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="exampleInputPassword1">Password</label>
                                                                <input type="password" class="form-control" placeholder="Senha Nova" name="password" id="exampleInputPassword1">
                                                                <input type="hidden" class="form-control" name="id" value="<?php echo $this->user['id']; ?>"  id="exampleInputPassword1">
                                                                <br>
                                                            </div>
                                                                <div class="col-sm-8">
                                                                    <button type="submit" class="btn btn-info">Atualizar</button>
                                                                </div>

                                                        </form>
                                                    </div>
                                        </section>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade in" id="tab5">
                    <br>

                    <div class="row" style="min-height:300px;">
                        <div  class="col-sm-12">
                            <div class="col-xs-8">
                                <!-- required for floating -->
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs tabs-left">
                                    <li class="active"><a href="#log" data-toggle="tab">Logo de Acesso</a></li>
                                    <li><a href="#profile3" data-toggle="tab">Actividades da Secretaria</a></li>
                                    <li><a href="#messages4" data-toggle="tab">Actividades dos Medicos</a></li>
                                    <li><a href="#settings5" data-toggle="tab">Actividades do Paciente</a></li>
                                </ul>
                            </div>
                            <div class="col-xs-12">
                                <!-- Tab panes -->
                                <div class="tab-content">


                                    <div class="tab-pane active" id="log">

                                        <?php $log = new \Ballybran\Helpers\Log\Log("logoAccess.txt");?>
                                        <p class="btn btn-danger"> <?php  echo  $log->open(); ?></p>
                                    </div>
                                    <div class="tab-pane" id="profile3">
                                        <?php $secret = new \Ballybran\Helpers\Log\Log("logActividadeCecretria.txt");
                                        echo  $secret->open();
                                        ?>
                                    </div>
                                    <div class="tab-pane" id="messages4">
                                        <?php $pacient = new \Ballybran\Helpers\Log\Log("logOfPaciente.txt");
                                        echo  $pacient->open();
                                        ?>
                                    </div>
                                    <div class="tab-pane" id="settings5">
                                        <?php $pacient = new \Ballybran\Helpers\Log\Log("logOfPaciente.txt");
                                        echo  $pacient->open();
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>
</div>

<script>
    var PieChart = {
        type: "pie",
        data: {
            datasets: [{
                data: [
                    [ <?php echo json_encode(count($novos));?>],
                    [ <?php echo json_encode(count($emEspera));?>],
                    [<?php echo json_encode(count($agendados));?>],
                    [<?php echo json_encode(count($atendidos));?>]
                ],

                backgroundColor: [
                    '#34495E',
                    '#F39C12',
                    '#419641',
                    '#E74C3C'
                ]
            }],
            labels: [
                ' Novos',
                ' Em espera',
                'Agendados',
                'Atendidos'
            ]

        },

        options: {
            responsive: true

        }
    };
    var pie = document.getElementById('barChart').getContext('2d');
    window.line = new Chart(pie, PieChart);

    var PieChartFunc = {
        type: "pie",
        data: {
            datasets: [{
                data: [
                    [<?php echo count($medicos); ?>], [<?php echo count($secretaria); ?>], [<?php echo count($laboratorio); ?>],

                ],

                backgroundColor: [
                    "#f7409e",
                    "#46BFBD",
                    "#949FB1"
                ]
            }],
            labels: [
                [' Medicos'],
                ['Secretaria'],
                ['Laboratorio']
            ]

        },

        options: {
            responsive: true
        }
    };
    var pieFunc = document.getElementById('barChartFunc').getContext('2d');
    window.line = new Chart(pieFunc, PieChartFunc);


    var ctx = document.getElementById("totalPaciente").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "julho", "Agosto", "Setembro", "Outrubro", "Novembro", "Dezembro"],
            datasets: [

                {
                    label: 'Pacientes não Atendidos',
                    data: [

                        [<?php echo json_encode(count($allPaciente[0]));?>],
                        [<?php echo json_encode(count($allPaciente[1]));?>],
                        [<?php echo json_encode(count($allPaciente[2]));?>],
                        [<?php echo json_encode(count($allPaciente[3]));?>],
                        [<?php echo json_encode(count($allPaciente[4]));?>],
                        [<?php echo json_encode(count($allPaciente[5]));?>],
                        [<?php echo json_encode(count($allPaciente[6]));?>],
                        [<?php echo json_encode(count($allPaciente[7]));?>],
                        [<?php echo json_encode(count($allPaciente[8]));?>],
                        [<?php echo json_encode(count($allPaciente[9]));?>],
                        [<?php echo json_encode(count($allPaciente[10]));?>],
                        [<?php echo json_encode(count($allPaciente[11]));?>]
                    ],


                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'

                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderWidth: 1
                },
                {
                    label: 'Atendidos',
                    data: [

                        [<?php echo json_encode(count($pacientesAtendidos[0]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[1]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[2]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[3]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[4]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[5]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[6]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[7]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[8]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[9]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[10]))?>],
                        [<?php echo json_encode(count($pacientesAtendidos[11]))?>]
                        ],


                    backgroundColor: [
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C"

                    ],
                    borderColor: [

                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C",
                        "#FDB45C"

                    ],
                    borderWidth: 1
                }]
        },
        scales: {
            yAxes: [{
                barPercentage: 0.5
            }]
        },

        options: {
            responsive: true
        }
    });


    var ctxAdmin = document.getElementById("totalFunc").getContext('2d');
    var AminChart = new Chart(ctxAdmin, {
        type: 'bar',
        data: {
            labels: [' Medicos', 'Secretaria', 'Laboratorio', 'enfermeiros'],
            datasets: [

                {
                    label: "Medicos",

                    data: [
                        [<?php echo count($medicos); ?>]
                    ],


                    backgroundColor: [
                        "#f7409e",

                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 2
                },
                {
                    label: "Secretaria",

                    data: [
                        [<?php echo count($secretaria); ?>]
                    ],


                    backgroundColor: [
                        "#46BFBD"

                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 2
                },
                {
                    label: "Laborátorio",

                    data: [
                        [<?php echo count($laboratorio); ?>]
                    ],


                    backgroundColor: [
                        "#949FB1"
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 2
                },
                {
                    label: "Enfermeiros",

                    data: [
                        [<?php echo count($enfermeiros); ?>]
                    ],


                    backgroundColor: [
                        "#aa45e7"
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 2
                }]
        },
        scales: {
            xAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Month'
                }
            }],
            yAxes: [{
                display: true,
                scaleLabel: {
                    display: true,
                    labelString: 'Value'
                }
            }]
        },

        options: {
            responsive: true
        }

    });

     var PieChartSexo = {
        type : "pie",
        data : {
            datasets: [{
                data :
                    [
                        [<?php echo json_encode(count($homem));?>],
                        [<?php echo json_encode(count($mulher));?>]


                    ],

                backgroundColor: [
                    "#1DC7EA",
                    "#f7409e"

                ],
            }],
            labels :


                [
                    'Homem',
                    ' Mulher'

                ]

        },

        options : {
            responsive : true
        }
    };
    var pies = document.getElementById('barSexo').getContext('2d');
    window.line = new Chart(pies, PieChartSexo);

</script>

<script>

    var monkeyList = new List('funclist', {
        valueNames: [
            'name',
            'lastname',
            'date',
            'especialidade',
            'aria'
        ]
    });


    var options = {
        valueNames: [    'name1',
            'date1',
            'status1',
            'aria1',
            'medico1']
    };

    // Init list
    var contactList = new List('pacilist', options);

    //    userList.add({ name: 'Leia', born: '1954', image: 'http://www.listjs.com/images/tests/leia.jpeg', id: 5, timestamp: '67893' });
</script>



<script>

    $(document).ready(function() {

        var localeCode = "pt-br";

            $.post( '<?php echo URL;?>account/getEvent2',
                function(data){
//                alert(data)

                    $('#calendar').fullCalendar({
                        header: {
                            left: 'prev,next today',
                            center: 'title',
                            right: 'month,agendaWeek,agendaDay'
                        },
                        buttonText: {
                            today:    'Hoje',
                            month:    'Mês',
                            week:     'Semana',
                            day:      'Dia'
                        },
                        theme: true,
                        themeSystem:'bootstrap3',
                        locale: localeCode,
                        defaultDate: new Date(),
                        navLinks: true, // can click day/week names to navigate views
                        editable: true,
                        selectable: true,
                        selectHelper: true,
                        allDaySlot: true,
//                    eventLimit: false, // allow "more" link when too many events
                        events: $.parseJSON(data),
//                    eventColor: '#378006',
                        eventDrop: function(event, delta, revertFunc){

                            var newId = event.id;
                            var newStard =$.fullCalendar.moment(event.start).format();
                            var newEnd = $.fullCalendar.moment(event.end).format();
                            var newTitle = event.title;

                            if (!confirm("Esta seguro??")) {
                                revertFunc();
                            }else{
                                $.post('<?php echo URL;?>Events/updatEvent',
                                    {
                                        id:newId,
                                        start:newStard,
                                        end:newEnd,
                                        title:newTitle
                                    },
                                    function(data){
                                        if (data == 1) {
                                            alert('Se actualizo correctamente');
                                        }
                                    });
                            }
                        },
                        eventResize: function(event, delta, revertFunc) {
                            var newId = event.id;
                            var newStard =$.fullCalendar.moment(event.start).format();
                            var newEnd = $.fullCalendar.moment(event.end).format();
                            var newTitle = "Consulta";



                            if (!confirm("Esta seguro de cambiar la fecha?")) {
                                revertFunc();
                            }else{
                                $.post('<?php echo URL;?>Events/updatEvent',
                                    {
                                        id:newId,
                                        start:newStard,
                                        end:newEnd,
                                        title:newTitle

                                    },
                                    function(data){
                                        if (data == 1) {
                                            alert('Se cambio correctamente');
                                        }
                                    });
                            }
                        },
                        eventClick: function(event, jsEvent, view) {

                            // alert(event.title);
                            $('#mhdnIdEvento').val(event.id);
                            $('#title').val(event.title);
                            $('#nome').html(event.firstname + " " + event.lastname);
                            $('#telefone').html(event.telephone);
                            $('#address_1').html(event.address_1);
                            $('#address_2').html(event.address_2);
                            $('#sexo').html(event.sexo);
                            $('#bairro').html(event.bairro);
                            $('#city').html(event.city);
                            $('#email').html(event.email);
                            $('#infos').html(event.info);
                            $('#id').html(event.usuarios_id);
                            $('#modalEvento').modal();

                            if (event.url) {
                                window.open(event.id);
                                return false;
                            }

                        },

                        eventAfterRender: function (event, element, view) {
                            var dataHoje = new Date();
                            if (event.start < dataHoje && event.end > dataHoje) {
                                //event.color = "#FFB347"; //Em andamento
                                element.css('background-color', '#FFB347');
                            } else if (event.start < dataHoje && event.end < dataHoje) {
                                //event.color = "#77DD77"; //Concluído OK
                                element.css('background-color', '#77DD77');
                            } else if (event.start > dataHoje ) {
                                //event.color = "#AEC6CF"; //Não iniciado
                                element.css('background-color', '#AEC6CF');
                            }
                        },

                        eventRender: function(event, element) {
                            var el = element.html();
                            element.html("<div style='width:90%;float:left;'>" + el + "</div>" +
                                "<div style='color:red;text-align:right;' class='closeE'>" +
                                "<i class='fa fa-trash'></i>" +
                                "</div>");

                            element.find('.closeE').click(function(){
                                if (!confirm("Esta seguro de eliminar el evento?")) {
                                    return false;
                                }else{
                                    var id = event.Paciente_id;

                                    $.post('<?php echo URL;?>Events/deleteEvent',
                                        {
                                            Paciente_id:id
                                        },
                                        function(data){
                                            if (data === 1) {
                                                $('#calendar').fullCalendar( 'removeEvents', event.Paciente_id);
                                                alert('Se elimino correctamente');
                                            }
                                        });

                                }

                            });
                        }

                    });
                });



    });

    //    var colorWell;
//    var defaultColor = "#0000ff";
//
//    window.addEventListener("load", startup, false);
//
//    function startup() {
//        colorWell = document.querySelector("#colorWell");
//        colorWell.value = defaultColor;
//        colorWell.addEventListener("input", updateFirst, false);
//        colorWell.addEventListener("change", updateAll, false);
//        colorWell.select();
//    }

</script>