<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

use Ballybran\Helpers\Security\Session;
use Module\menu\Sub_Menu;
use Ballybran\Library\Form;
Sub_Menu::getSubMenu();
?>


<div class="container" id="features" >
    <div class="breadcrumb text-center" id="features">
        <strong>Dados do Paciente</strong>
    </div>
    <div class="row ">

        <div class="col-lg-3 4u 12u(mobile)">


            <?php  if (!empty($this->UserPhoto['path'])) { ?>

                <img  src="<?php echo URL . $this->UserPhoto['path']; ?>" class="col-lg-7 image img-responsive img-thumbnail" alt="<?php echo $this->UserPhoto['name']; ?>" />
                <?php
                if (Session::exist()) {
                    ?>
                    <a href="<?php echo URL; ?>account/deleteImage"  class="glyphicon glyphicon-remove" >delete</a>
                    <?php

                }
            } else {
                echo "nao tem imagem";
            } ?>
        </div>

        <div class="col-lg-4 4u 12u(mobile) text-left">
            <h3>Contacto</h3>

            <strong>Nome: </strong><?php echo  $this->user['firstname'] . "\t" .  $this->user['lastname']; ?><br>
            <strong>Telefone: </strong><?php echo  $this->user['telephone']; ?><br>
            <strong>Email: </strong><?php echo  $this->user['email']; ?><br>

        </div>

        <div class="col-lg-4 4u 12u(mobile) text-left">
            <h3>Endereço</h3>

            <strong>Endereço 1: </strong><?php echo  $this->user['address_1']; ?><br>
            <strong>Endereço 2: </strong><?php echo  $this->user['address_2']; ?><br>
            <strong>Cidade: </strong><?php echo  $this->user['city']; ?><br>
            <strong>País: </strong><?php echo  $this->user['country_id']; ?><br>
        </div>

    </div>
</div>
<div class="container" id="features" >
    <div class="col-lg-12 4u 12u(mobile)">
        <div class="breadcrumb text-center" id="features">
            <strong>PRONTUÁRIO DO PACIENTE</strong>
        </div>
            <table class="table table-black table-responsive table-bordered">
                <h3>Medicação</h3>
                <thead>
                <tr>
                    <th>Nome Generico</th>
                    <th>Nome Comercial</th>
                    <th>Dose</th>
                    <th>Via de Administração</th>
                    <th>Data de Início</th>
                    <th>Data do Fim</th>
                    <th>Intervalo</th>
                    <th>Médico</th>
                    <th>Resultado</th>
                </tr>
                </thead>
                <tbody>
                    <tr>

                    </tr>

                </tbody>
            </table>

            <table class="table table-black table-bordered">
                <h3>Exames</h3>

                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Sexo</th>
                    <th>Data</th>
                    <th>Resultado</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                </tr>

                </tbody>
            </table>
        </div>
</div>
