<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */
use Ballybran\Helpers\Security\Session;
use Module\Clinic\Lib\menu\Sub_Menu;
use Ballybran\Library\Form;
Sub_Menu::getSubMenu();

?>

    <section>
        <div class="container">
            <section>
                <div class="page-header btn-default text-center" id="contact">
                    <h2>Horarios<small></small></h2>


                            <table class="col-lg-4 table  table-black table-bordered table-responsive pull-right">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Horas de Atendimento</th>
                                    <th>Dia da Semana</th>
                                    <th>Atualizar</th>
                                    <th>Deletar</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($this->horario as $key => $item) : ?>
                                <tr>
                                    <?php echo Form::open(['action'=> URL .'account/updateHorario', 'method'=> 'post']); ?>
                                    <th scope="row"><?php echo $key + 1  ?></th>
                                    <td><?php echo Form::input(['type'=> 'time', 'name'=> 'hora','style'=>'color:#000000;', 'value'=>  $item['hora']]); ?></td>
                                    <td><?php echo Form::input(['type'=> 'text', 'name'=> 'diaSeman','style'=>'color:#000000;', 'value'=>  $item['diaSeman']]); ?></td>
                                    <?php echo Form::input(['type'=> 'hidden', 'name'=> 'id', 'value'=>  $item['id']]); ?>
                                    <td><?php echo Form::submit(['type'=> 'submit', 'value'=> 'Atualizar']); ?></td>
                                    <?php echo Form::close(); ?>
                                    <td><a href="<?php echo URL;?>account/deteleHoraroById/<?php echo $item['id']?>"><i class="glyphicon glyphicon-trash"></i></a></td>

                                </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                </div>

                <?php if(Session::get('role') == 'funcionario') : ?>
                <div class="col-lg-3" style="margin-left: 36%;" >
                    <?php echo Form::open(['action'=> URL .'account/insertHorario', 'method'=> 'post']); ?>
                    <?php echo Form::input(['type'=> 'time', 'name'=> 'hora', 'placeholder'=>  '00-00']); ?>
                    <?php echo Form::input(['type'=> 'text', 'name'=> 'diaSeman', 'placeholder'=> 'Dia da Semana' ]); ?>
                    <?php echo Form::input(['type'=> 'hidden', 'name'=> 'usuarios_id', 'value'=>  Session::get('ID')]); ?>
                    <?php echo Form::submit(['type'=> 'submit', 'value'=> 'Adicionar']); ?>
                    <?php echo Form::close(); ?>
                </div>
                <?php endif; ?>
            </section>
        </div>
    </section>



