<?php
/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

use Ballybran\Helpers\Security\Session;
use Module\menu\Sub_Menu;

Sub_Menu::getSubMenu();

?>

<div class="container">
    <section>
        <div class="page-header text-center btn-default">

            <form method="POST" action="<?php echo URL; ?>account/insertImageUser" enctype="multipart/form-data">
                <label for="pic">Faça o Uploads de uma foto para o perfil:</label>
                <input type="file" name="archive[]" id="pic" />
                <input type="submit" value="Carregar" />
            </form>
        </div>
    </section>
</div>
