<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */
use Ballybran\Helpers\Security\Session;
use Module\Clinic\Lib\menu\Sub_Menu;

Sub_Menu::getSubMenu();

?>

<div class="col-sm-12">

    <section>
        <div class="container">
            <section>
                <div class="page-header btn-default text-center" id="contact">
                    <h3>Actualize Password </h3>
                </div> <!-- End Page Header -->
                <div class="row">


                    <div class="row">
                        <div class="col-lg-12">
                            <form  class="form-horizontal" name="perfil" method="post">


                                <!-- <div class="form-group">
                                    <label for="user-url" class="col-lg-2 control-label">Password Antiga</label>
                                    <div class="col-lg-10">
                                        <input type="password" class="form-control" value="" name="password2" id="user-url">
                                    </div>
                                </div>  -->



                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password</label>
                                        <input type="password" class="form-control" value="" name="password" id="exampleInputPassword1">
                                        <br>
                                    <div class="col-sm-8">
                                        <button type="submit" class="btn btn-info" onclick="updateUser(<?php echo $this->UserData['id']; ?>)" >Atualizar</button>
                                    </div>

                                </div> 

                            </form>
                        </div>
                    </div>
            </section>


            <script>

                function updateUser(id) {


                    var password = $('form[name=perfil] input[name=password]')[0].value;
                    password = (password != "<?php echo $this->UserData['password'] ?>" && password != '') ? password : "<?php echo $this->UserData['password'] ?>";


                    $.ajax({
                        type: "post",
                        url: "<?php echo URL; ?>account/managePassword",
                        data: {id: id, password: password, }
                    }).done(function (resposta) {
                        if (resposta == true) {
                            alert(" atualizado com sucesso");
                        }

                    });

                    alert("vc vai atualizar o usuario com o id:" + id);
                }


                $(function () {

                    $('.deletar').click(function (e) {
                        var c = confirm("Tens a certeza que quer deletar?");
                        if (c == false)
                            return false;

                    });

                });


            </script>


