<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

use Ballybran\Helpers\Security\Session;
use Module\menu\Sub_Menu;
use Ballybran\Library\Form;
Sub_Menu::getSubMenu();
?>


<div class="container" id="features" >
    <div class="breadcrumb " id="features">
        <strong> <h3>Prontuário do paciente</h3></strong>
    </div>
    <div class="row ">

        <div class="col-lg-3 4u 12u(mobile) text-left">
            <h3>Dados do Paciente</h3>
                <?php  foreach ($this->paciente as $key => $value) { ?>

            <strong>Nome: </strong><?php echo  $value['firstname'] . "\t" .  $value['lastname']; ?><br>
            <strong>Telefone: </strong><?php echo  $value['telephone']; ?><br>
            <strong>Email: </strong><?php echo  $value['email']; ?><br>
            <strong>Informação: </strong><br><textarea cols="40" rows="10 " disabled="disabled"><?php echo  $value['info']; ?></textarea><br>
            <?php  } ?>
            <ul class="actions">
                <li><a href="#" class="button icon fa-file">Contacta-me</a></li>
            </ul>
        </div>
        <div class="col-lg-9 4u 12u(mobile)">

            <table class="table table-black table-bordered">
                <h3>Exames</h3>

                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Data</th>
                    <th>Resultado</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->getExame as $k => $va) {?>

                    <tr>
                        <td scope="row"><?php echo $k + 1; ?></td>
                        <td> <?php echo $va['nome']; ?></td>
                        <td> <?php echo $va['data']; ?></td>
                        <td> <?php echo $va['resultado']; ?></td>
                    </tr>

                <?php } ?>

                </tbody>
            </table>

            <table class="table  table-black table-bordered">
                <h3>Medicação</h3>
                <thead>
                <tr>
                    <th>Nome Generico</th>
                    <th>Nome Comercial</th>
                    <th>Dose</th>
                    <th>Via de Administração</th>
                    <th>Data de Início</th>
                    <th>Data do Fim</th>
                    <th>Intervalo</th>

                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->medical as $item => $value) {?>
                    <tr>
                        <td><?php echo $value["generico"]; ?></td>
                        <td><?php echo $value["comercial"]; ?></td>
                        <td><?php echo $value["dose"]; ?></td>
                        <td><?php echo $value["via_admin"]; ?></td>
                        <td><?php echo $value["inicio"]; ?></td>
                        <td><?php echo $value["final"]; ?></td>
                        <td><?php echo $value["interval"]; ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="container" id="features" >
    <div class="row ">

        <div class="col-lg-6 4u 12u(mobile)">

            <h3>Inserir Receita</h3>
            <?php
            foreach ($this->paciente as $key => $value ) {?>
                <div class="6u 12u(mobile)">
                    <section>
                        <form method="post" action="<?php echo URL; ?>funcionario/inserMedicamento">
                            <div class="row 50%">
                                <div class="6u 12u(mobile)">
                                    <input  name="generico" placeholder="Nome Generico" type="text" />
                                </div>
                                <div class="6u 12u(mobile)">
                                    <input name="comercial" placeholder="Nome Comercial" type="text" />
                                </div>
                            </div>
                            <div class="row 50%">
                                <div class="6u 12u(mobile)">
                                    <input  name="dose" placeholder="Dose" type="text" />
                                </div>
                                <div class="6u 12u(mobile)">
                                    <input name="via_admin" placeholder="Via de Administração" type="text" />
                                </div>
                                <div class="6u 12u(mobile)">
                                    <input name="interval" placeholder="Regra da Medicação" type="text" />
                                </div>
                            </div>
                            <div class="row 50%">
                                <div class="6u 12u(mobile)">
                                    <input  name="Funcionarios_id" value="<?php echo $value['Funcionarios_id']; ?>" type="hidden" />
                                </div>
                                <div class="6u 12u(mobile)">
                                    <input name="Paciente_id" value="<?php echo $value['Paciente_id']; ?>" type="hidden" />
                                </div>
                            </div>
                            <div class="row 50%">
                                <div class="6u 12u(mobile)">
                                    <input  name="inicio" placeholder="Data de inicio" type="text" />
                                </div>
                                <div class="6u 12u(mobile)">
                                    <input name="final" placeholder="data fim" type="text" />
                                </div>

                            </div>

                            <div class="row 50%">
                                <div class="12u">
                                    <button class="form-button-submit button icon fa-envelope">submeter</button>
                                </div>
                            </div>
                        </form>
                    </section>
                </div>
            <? }
            ?>


        </div>


        <div class="col-lg-6 4u 12u(mobile) text-left">

            <h3>Inserir Exame</h3>

            <div class="6u 12u(mobile)">
                <section>

                    <form method="post" action="<?php echo URL; ?>funcionario/inserirExame">
                        <div class="row 50%">
                            <div class="6u 12u(mobile)">
                                <input  name="nome" placeholder="Nome" type="text" />
                            </div>
                            <div class="6u 12u(mobile)">

                                <input type="hidden"  name="Paciente_id" value="<?php echo $this->paciente[0]['Paciente_id'];?>" />

                                <input  name="data" placeholder="Data do Exame" type="text" />
                            </div>
                        </div>
                        <div class="row 50%">

                            <div class="6u 12u(mobile)">
                                <button class="form-button-submit button icon fa-envelope">submeter</button>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
        </div>

</div>
