<?php
/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */
\Module\Clinic\Lib\menu\Sub_Menu::getSubMenu();
?>


<section>
    <div class="container col-sm-12">
        <div class="breadcrumb text-center" id="features">
            <strong> <h3>Consultas marcadas e não atendidas</h3></strong>
        </div>

        <table class="col-lg-12 table  table-black table-bordered table-responsive pull-right">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Telefone</th>
                    <th>Tipo</th>
                    <th>Informação</th>
                    <th>Médico</th>
                    <th>Fazer o Exame</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->list as $key => $value) { ?>
                    <tr>
                        <td><?php echo $value['firstname'] . "\n" . $value['lastname']; ?></td>
                        <td><?php echo $value['telephone']; ?></td>
                        <td><?php echo $value['role']; ?></td>
                        <td><?php echo $value['info']; ?></td>
                        <td><?php echo $value['titulo']; ?></td>

                        <td> <a class="btn btn-success glyphicon glyphicon-edit" id="edita" href="<?php echo URL; ?>laboratorio/exame/<?php echo $value['usuarios_id']; ?>"></a></td>
                    </tr>
                <?php } ?>

            </tbody>
        </table>
        <?php if ($this->list == "" || empty($this->list)) echo "<h3>Não têm  pacientes hoje! :/</h3>"; ?>

    </div>
</section><!-- Call to action -->
