<?php

/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */
use Ballybran\Helpers\Security\Session;
?>


<nav class="navbar navbar-default ">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#amyNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="amyNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo URL; ?>account/cpanel">Painel</a></li>

                <?php
                if (Session::exist()) :
                    if (Session::get('role') == 'admin' || Session::get('role') == 'owner' || Session::get('role') == 'markting') :
                        ?>

                        <li class="nav-item" >
                            <a  class="nav-link" href="<?php echo URL; ?>article/publish">Publicar Artigo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo URL; ?>faq/insertFaq">Inserir Faq</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo URL; ?>contacto/contactoinfo">Atualizar Contacto</a>
                        </li>
                    <?php
                    endif;

                    if (Session::get('role') == 'owner') :
                        ?>

                        <li class="nav-item" >
                            <a  class="nav-link" href="<?php echo URL; ?>finance">Finanças</a>
                        </li>


                    <?php
                    endif;

                    if (Session::get('role') == 'laboratorio'):
                        ?>

                        <li class="nav-item" >
                            <a  class="nav-link" href="<?php echo URL; ?>laboratio">Ver Exames</a>
                        </li>

                    <?php
                    endif;

//                    if (Session::get('role') == 'paciente') :
                    ?>
                    <!--                        <li class="nav-item" >-->
                    <!--                            <a class="nav-link" href="--><?php //echo URL; ?><!--paciente"><span>Marcar uma consulta</span></a>-->
                    <!--                        </li>-->
                    <!---->
                    <!--                    --><?php
            //endif;

            endif;
                ?>
            </ul>
        </div>
    </div>
</nav>
<div class="container" id="features" >
    <hr>

