
<div id="features-wrapper">

    <section id="features" class="container">
        <div class="breadcrumb text-center">
            <?php foreach ($this->categoryByNameTitle as $key => $values) : ?>
                <strong><a href="<?php echo URL; ?>categorias">CATEGORIAS</a></strong> /<i> <?php echo $values['nome']; ?></i>
            <?php endforeach; ?>

        </div>
        <div class="row ">

            <?php
            $page = new \Ballybran\Helpers\Event\Paginator('PDO', "SELECT * FROM categoria inner join article on categoria.id_cat = article.id_cat WHERE categoria.nome ='$this->nameOfTheCategorie' ORDER BY categoria.nome DESC", 6);
            foreach ($page->getColum() as $key => $value) :
                ?>
                <div class="col-lg-4 ">
                    <?php if (empty($value['path'])) { ?>

                        <img class="img-thumbnail" style="height: 200px;" src="<?php echo URL . DIR_FILE . 'Public/images/default-article-img.jpg' ?>" >
                    <?php } else { ?>
                        <img class="img-thumbnail" style="height: 200px;" src="<?php echo URL . $value['path']; ?>" >
                    <?php } ?>

                    <h4><?php echo $value['title']; ?></h4>
                    <p><?php echo $value['excerpt']; ?></p>
                    <div class="group">
                        <a href="<?php echo URL; ?>article/art_pre_post/<?php echo $value['id_article']; ?>" class="btn btn-primary">Ler Mais</a>
                    </div>
                </div>

            <?php endforeach; ?>
        </div>
        <div class="text-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <?php echo $page->pagination(); ?>
                </ul>
            </nav>
        </div>
    </section>
</div>
