

<div id="features-wrapper">

    <section id="features" class="container">
        <div class="breadcrumb text-center">
            <strong>CATEGORIAS</strong>
        </div>
        <div class="row ">

            <?php
            $page = new \Ballybran\Helpers\Event\Paginator('PDO', "SELECT * FROM categoria  WHERE id_cat ORDER BY id_cat DESC", 4);

            foreach ($page->getColum() as $key => $value) :
                ?>
                <div class="col-lg-4">
                    <header class="panel-heading header-title text-center">
                        <h4><?php echo $value['nome']; ?></h4>
                    </header>
                    <?php if (empty($value['path'])) { ?>

                        <img class="img-thumbnail" style="height: 200px;" src="<?php echo URL . DIR_FILE . 'Public/images/default-article-img.jpg' ?>" >
                    <?php } else { ?>
                        <img class="img-thumbnail" style="height: 200px;" src="<?php echo URL . $value['path']; ?>" >
                    <?php } ?>
                    <p><?php echo $value['description']; ?></p>
                    <div class="group">
                        <?php $NameCat = str_replace(" ", "-", $value['nome']); ?>
                        <a href="<?php echo URL; ?>Categorias/getCategoryById/<?php echo $NameCat; ?>" class="btn btn-primary">Ler Mais</a>

                    </div>
                </div>

            <?php endforeach; ?>
        </div>
        <div class="text-center">

            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <?php echo $page->pagination(); ?>
                </ul>
            </nav>
        </div>
    </section>
</div>


