<?php
/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

echo Module\Lib2\header::getHeader();

?>


<div class="container">
    <section>
        <div class="page-header" id="features">
            <!-- <h2>FAQ.<small>Perguntas Mais Frequentes</small></h2> -->
        </div><!-- End page header -->

        <?php
// foreach ($this->Allfoot as $key => $value) :
        foreach ($this->notCat as $key => $values) :
            $da = str_replace(' ', '', $values['name']);
            ?>

            <a href="<?php echo URL; ?>Article/art_pre_post/<?php echo $values['id_article']; ?>" class="btn btn-danger"><?php echo $values['title']; ?></a>

        <?php endforeach; ?>


<?php Module\Lib2\header::getFooter();

