<?php
/**
 * KNUT7 K7F (http://framework.artphoweb.com/)
 * KNUT7 K7F (tm) : Rapid Development Framework (http://framework.artphoweb.com/)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @link      http://github.com/zebedeu/artphoweb for the canonical source repository
 * @copyright (c) 2015.  KNUT7  Software Technologies AO Inc. (http://www.artphoweb.com)
 * @license   http://framework.artphoweb.com/license/new-bsd New BSD License
 * @author    Marcio Zebedeu - artphoweb@artphoweb.com
 * @version   1.0.2
 */

/**
 *
 * Tinymce styple
 *
 * */
use Ballybran\Helpers\Copyright\Copyright;

?>
<footer class="footer panel-footer text-center ">
    <?php echo  Copyright::copyright(null, 'KNUT 7 FRAMWORK') . '<br>';
    echo \Ballybran\Helpers\System::time_start();
    echo \Ballybran\Helpers\System::http_user_agent();
    echo \Ballybran\Helpers\Time\Timestamp::dataTime();
    ?>

</footer>
<!-- Bootstrap -->

<script src="<?php echo URL; ?>Public/js/bootstrap.js"></script>

<!--- Clinic -->
<script src="<?php echo URL. DIR_FILE;?>Public/clinic/assets/js/jquery.dropotron.min.js"></script>
<script src="<?php echo URL. DIR_FILE;?>Public/clinic/assets/js/skel.min.js"></script>
<script src="<?php echo URL. DIR_FILE;?>Public/clinic/assets/js/skel-viewport.min.js"></script>
<script src="<?php echo URL;?>Public/js/tether.js"></script>

<script src="<?php echo URL.DIR_FILE; ?>Public/fullcalendar/lib/moment.min.js"></script>
<script src="<?php echo URL.DIR_FILE; ?>Public/fullcalendar/locale/pt.js"></script>
<!--<script src="--><?php //echo URL.DIR_FILE; ?><!--Public/fullcalendar/gcal.js"></script>-->
<script src="<?php echo URL.DIR_FILE; ?>Public/fullcalendar/fullcalendar.js"></script>
<!--<script src="--><?php //echo URL.DIR_FILE; ?><!--Public/clinic/assets/js/script.js"></script>-->

<script src="<?php echo URL. DIR_FILE;?>Public/clinic/assets/js/util.js"></script>
<!--[if lte IE 8]><script src="<?php echo URL. DIR_FILE;;?>Public/clinic/assets/js/ie/respond.min.js"></script><![endif]-->
<script src="<?php echo URL. DIR_FILE;?>Public/clinic/assets/js/main.js"></script>
<script src="<?php echo URL . DIR_FILE?>Public/js/jquery.searchable-1.1.0.min.js"></script>
</body>
</html>